### ISSUE TITLE
UTC showing in frontend in some browsers

### ISSUE THREAD

**Issue by mitchellross** [home-assistant/frontend#10502]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Since updating to 2021.10.x (and now 2021.11) - various browsers attached to my Supervised install have been using UTC rather than local Sydney/Australia time. This has meant that yesterday's weather has been displayed etc. 

I have replicated this issue on completely fresh install of Debian & Supervised and looking at the logs or any card dependent on timings (like weather) on Firefox on the host machine. Likewise, pointing my Fire HD10 (2019) at that instance shows this behaviour in both Fully Kiosk and the Companion App. 

"Updating" to 2021.9.7 fixes this issue. 

The issues do not appear on Chrome or Safari. 

As an example of this issue, this is a screenshot of the logs section of Supervisor. You can see that the summary entries are appearing in UTC, while the detailed entries below are in local time. This did not occur prior to 2021.10.x.

(https://user-images.githubusercontent.com/39319760/139831303-deb733d9-d648-498a-ad94-f6260ca7b0b7.png)

### Describe the behavior you expected

I would expect to see a consistent application of local time at the front end of all devices and all browsers, as was the case on 2021.9.7.

### Steps to reproduce the issue

1. Point an impacted browser (Firefox, Amazon Webview based apps etc) at any HA instance from 2021.10.x onwards
2. Check to see whether the front end displays things like the logs, or weather forecasts in local time.
3.
...

### What version of Home Assistant Core has the issue?

2021.10.1 onwards

### What was the last working version of Home Assistant Core?

core-2021.9.7

### In which browser are you experiencing the issue with?

Various - see above

### Which operating system are you using to run this browser?

Debian Bullseye / FireOS in my own testing

### State of relevant entities

```txt
n/a
```

### Problem-relevant frontend configuration

```yaml
No changes made to config.yaml to replicate this issue. Everything left as vanilla as possible to eliminate any other interactions causing the issue. (Only added HACS to get my local weather sensors into the weather card).
```

### Javascript errors shown in your browser console/inspector

```txt
nil
```

### Additional information

Happy to undertake any further testing or turn on debug logging on any device if it helps.

Here is the same screenshot as above, but following a downgrade to 2021.9.7 - you'll see that local time is consistently shown. Obviously it doesn't really matter that these aren't the same - but it is an issue when time critical cards like weather forecasts are displaying UTC rather than the local time.

![Screenshot from 2021-11-02 21-56-57](https://user-images.githubusercontent.com/39319760/139834148-18043a79-be01-4652-bb52-c946dad25966.png)

**Comment by bramkragten** [comment]
It is known that this issue is present in 2021.10, the current beta, 2021.11, should fix it.

**Comment by mitchellross** [comment]
I replicated the issue in the beta channel as well. Sorry should have mentioned that.

**Comment by mitchellross** [comment]
I can confirm that this issue persists on 2021.11.

Here is HA late on Thursday night, happily displaying yesterday's weather on version 2021.11. 

![Screenshot from 2021-11-04 22-34-28](https://user-images.githubusercontent.com/39319760/140306982-9caa55af-9819-4484-aa93-c0dc4e541e95.png)

Here is the logbook - check out the difference between the times shown and the system time.

![Screenshot from 2021-11-04 22-38-47](https://user-images.githubusercontent.com/39319760/140307380-6f9ee3ef-990d-40a7-a8ca-97e4b20a5949.png)

**Comment by TheFuzz4** [comment]
I also am now facing this issue.  Everything in my Frontend shows up in UTC time.  
![image](https://user-images.githubusercontent.com/325957/141024927-6c5a3042-a983-4db4-8dc0-d4bd13cf83b7.png)
I am in Denver Time as you can see from my task bar but the FE shows UTC

**Comment by mitchellross** [comment]
> 
> 
> I also am now facing this issue. Everything in my Frontend shows up in UTC time. ![image](https://user-images.githubusercontent.com/325957/141024927-6c5a3042-a983-4db4-8dc0-d4bd13cf83b7.png) I am in Denver Time as you can see from my task bar but the FE shows UTC

I *think* this is fixed in 2021.11.4 - can you confirm?

**Comment by TheFuzz4** [comment]
I can confirm this is now fixed. Thank you.  Sorry for the delayed response was out of town.

**Comment by mitchellross** [comment]
@bramkragten Thanks for your efforts. All behaving as expected now.
