### ISSUE TITLE
Can't create non-english lovelace dashboard name

### ISSUE THREAD

**Issue by havivi86** [home-assistant/frontend#10557]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

when trying to create new lovelace dashboard with Hebrew name, it can't be saved. I need to push at least 1 English letter in order to save it.
for example, dashboard with name of: "שלום".

### Describe the behavior you expected

To be able to save the dashboard with any name that I want.

### Steps to reproduce the issue

1. Go do the lovelace dashboards in the configurations.
2. Try to create new dashboard with the name "שלום".

### What version of Home Assistant Core has the issue?

core-2021.10.6

### What was the last working version of Home Assistant Core?

core-2021.10.6

### In which browser are you experiencing the issue with?

Edge and Chrome

### Which operating system are you using to run this browser?

Windows 11

### Javascript errors shown in your browser console/inspector

```txt
I think this is because some internal regex that removes the Hebrew letters from the URL, at slugify.ts file. The line that:
    .replace(/[^\w-]+/g, "") // Remove all non-word characters
This removed the Hebrew letters.
```

**Comment by spacegaier** [comment]
Works fine for me in 2021.11. I fixed a few issues with the regex in that release, which perhaps also come into play here (don't remember the details right now).

**Comment by havivi86** [comment]
Thanks @spacegaier for replying!
unfortunately, I'm on the latest version, and still have the issue:
![image](https://user-images.githubusercontent.com/39840360/140621170-0f48f813-ee4e-47a3-afe6-9c4c5b5c582e.png)
when I try to create with English name, I have no issues:
![image](https://user-images.githubusercontent.com/39840360/140621181-6bc97597-2d7c-4725-b20b-2b179b5fe6a7.png)

**Comment by spacegaier** [comment]
Ah, you are not in "Advanced mode" which is why you do not see the third input field where a URL has to be specified. In non-advanced mode, the system tries to automatically fill it, but with the Hebrew characters this does not work. In my tests I manually inserted a value there and then it worked fine.

**Comment by havivi86** [comment]
I think that having the URL visible in any configuration is better then current situation (I wouldn't get stuck here if that was the case).
Event better solution (if I'm not missing anything) might be - I noticed that some part in HA knows how to translate Hebrew into English letters Hebrew. I noticed it when I have 2 phones connected with Hebrew names, I have separate service to send notification for each one of the phones. The service name for the phones are generated from the Hebrew somehow. If that's applicable, this can be cool solution.

**Comment by matthiasdebaat** [comment]
If we could translate it to an English URL that would be the best option in my opinion. I would like to keep the URL input hidden for non-advanced mode users.

**Comment by spacegaier** [comment]
I have honestly no idea where and how this translation takes place. The phones/devices themselves still have a Hebrew name?

**Comment by havivi86** [comment]
> I have honestly no idea where and how this translation takes place. The phones/devices themselves still have a Hebrew name?

no, the translation is made somewhere inside HA. no idea where... :(
But so I'll be clear about what I'm meaning, for example, I have phone called "טלפון בבי" (the name was given only in HA):
![image](https://user-images.githubusercontent.com/39840360/140805037-c302973f-cd16-4022-a0ef-000b6a94d47a.png)

When I checked my services, I see the following notification service:
![image](https://user-images.githubusercontent.com/39840360/140805346-bb26f014-9cf7-41d0-ade7-c76cf20d6dac.png)
where "tlpvn_bby" inside "mobile_app_tlpvn_bby" is somehow corresponding the Hebrew name I gave the device - 
"טלפון" and "tlpvn" both 5 letters, same as "בבי" and "bby", and the English word actually sounds somehow like the Hebrew word. So translation does exists somewhere, but I don't know where.
