### ISSUE TITLE
Its almost impossible to add an entity or device to an automation, script, scene, etc. from the iOS UI.

### ISSUE THREAD

**Issue by brian1917** [home-assistant/frontend#10855]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When on the iOS client (app or browser on iPhone), it's very difficult to add an entity or device to an automation, scene, etc. For example, I start typing "Christmas" for finding my "Christmas Tree", the UI shows "Christmas Tree" but when I click it nothing happens and the list goes away and I need to try again. It works maybe 1 every 10 times.

### Describe the behavior you expected

To be able to select entities on the front-end.

### Steps to reproduce the issue

1. Edit an automation in the iOS UI.
2. In an action, select an entity.
3. See if it selects or just goes away.

### What version of Home Assistant Core has the issue?

core-2021.11.3

### In which browser are you experiencing the issue with?

iOS - all versions.

### Which operating system are you using to run this browser?

iOS

**Comment by maartenhendrix** [comment]
When I scroll so the keyboard closes you can select an entity. At least this works for me as a workaround.

**Comment by SamuelMezger** [comment]
Here's a video of it happening:

https://user-images.githubusercontent.com/51318535/146082329-82d55af3-d5a2-4d40-accf-0cc51203f038.mp4

iOS 15.1

**Comment by AiYoriAoshi** [comment]
> When I scroll so the keyboard closes you can select an entity. At least this works for me as a workaround.

sometimes I somehow manage to close the keyboard and the select list stays but most of times the list just disappears with the keyboard. Really frustrating stuff, can't use the search at all

**Comment by AiYoriAoshi** [comment]
Problem still persists
Core-2022.4.5
Supervisor-2022.04.0
HAOS 7.6
Companion 2022.358

**Comment by melyux** [comment]
I read somewhere this was fixed in 2022.4, but it's not. It's there and it's incredibly aggravating.

**Comment by pentoo1989** [comment]
still there in 2022.4.7

**Comment by mikalauskas** [comment]
this issue is present since 0.x versions and still present on 2022.5.5. Never seen it fixed

**Comment by hughsaunders** [comment]
@melyux, yep still happening for me on 2022.9.7

**Comment by fbradyirl** [comment]
Still happening.

**Comment by melyux** [comment]
Haven't checked the latest version yet

**Comment by vilhalmer** [comment]
Still an issue.

**Comment by melyux** [comment]
How's it?

**Comment by hco** [comment]
The issue still exists.
Could you give me a pointer to the component that’s responsible?

I am a frontend developer and use iOS, maybe I can fix it, but I don’t know my way around the HA frontend codebase :)

**Comment by melyux** [comment]
Still happens on many places. Seems fixed on some of them but not most of them.

**Comment by MikeVensel** [comment]
This is still happening on 2024.11 in at least the automation and script editors. I think I’ve also still seen it happen when trying to edit dashboards recently as well. People are exclusively using tablets and phones to do everything so I feel that this REALLY needs to be addressed.

**Comment by melyux** [comment]
2025 and still happening. How hard is it to make a dropdown work?

**Comment by melyux** [comment]
Still happening.

**Comment by MikeVensel** [comment]
This seems like it **might** actually be fixed now with the rework to dropdowns that was done in one of the latest versions of Home Assistant. I checked briefly and it seemed like it was working.
