### ISSUE TITLE
Button entity: unexpected behaviour in android app

### ISSUE THREAD

**Issue by Vrobenmat** [home-assistant/frontend#10907]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Using a button entity in a normal entities card, clicking 'press' through a desktop browser interface triggers the button, as expected. 
Through the android app interface and mobile browsers, touching 'press' pulls up the entity details instead of triggering the button. This is not expected.

### Describe the behavior you expected

touching 'press' of a button entity in a lovelace entities card, in the android app, should trigger the button.

### Steps to reproduce the issue

1. Create a button entity, in my case coming from ESPHome
2. Add the button entity to an entities card
3. attempt to touch 'press' through the android app
...

### What version of Home Assistant Core has the issue?

2021.12.1

### In which browser are you experiencing the issue with?

Android app - 2021.10.0-full

### Which operating system are you using to run this browser?

Android 11

**Comment by Vrobenmat** [comment]
Sorry, wanted to move it to android but my GitHub fu is no good.

**Comment by Vrobenmat** [comment]
Directly in Chrome on android, same unexptected behaviour, i.e. 'press' pulls up the entity details.

**Comment by dshokouhi** [comment]
> Sorry, wanted to move it to android but my GitHub fu is no good.



> Chrome and Firefox on android, both in mobile and desktop view, same unexptected behaviour, i.e. 'press' pulls up the entity details.

As you can reproduce using a browser, this issue should not be moved.  Also only team members can move issues, normal users cannot.

**Comment by robertboccia** [comment]
Same issue for me this is a pretty big issue

**Comment by p4sI** [comment]
This is not only for Buttons, but also for Switches e.g. in EntitiesCard
![image](https://user-images.githubusercontent.com/5518425/146343711-995798f0-9a18-4fd8-bd79-42fb5d25e556.png)
If I click on the switch on the browser with the mouse it works fine. If I go to mobile mode (or on the phone) and touch it, the details view opens.

Not sure if it can be fixed together, otherwise I can open a new ticket for it. Just let me know.

**Comment by Jpsy** [comment]
> This is not only for Buttons, but also for Switches e.g. in EntitiesCard

Can't confirm that. 
The issue is alive and kicking for any button entities placed in entities cards but not for switches.

**Comment by robertboccia** [comment]
why is this issue closed?

**Comment by ludeeus** [comment]
Because a fix has been merged.

**Comment by p4sI** [comment]
> > This is not only for Buttons, but also for Switches e.g. in EntitiesCard
> 
> Can't confirm that. The issue is alive and kicking for any button entities placed in entities cards but not for switches. (Tested using Chrome dev tools on desktop browser to change between mobile view and desktop view.)

Sorry maybe I used the wrong term with "Switch", the html element is called "basic-switch". As you can see in my screenshot, it was a "toggle-button" or whatever its called for an automation. This got fixed in the PR and works now. Thanks :)

**Comment by robertboccia** [comment]
Still not working on multi entity row

Robert Boccia
________________________________

**Comment by p4sI** [comment]
> Still not working on multi entity row Robert Boccia
>
Which frontend version do you use? The PR was merged into 20211220.0 so you may need to update your system.

**Comment by robertboccia** [comment]
Update to hacs item has now resolved issue

Robert Boccia
________________________________
