### ISSUE TITLE
disabled device entities turn invisible upon revealing them

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#11067]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

selecting the disabled device entities turn invisible within a moment after clicking the `+ 4 disabled entities`

![Jan-01-2022 12-01-24](https://user-images.githubusercontent.com/33354141/147849130-47c34ad2-b13b-4a4a-8658-38bfc6a52ec1.gif)

### Describe the behavior you expected

have the disabled entities listed nicely

### Steps to reproduce the issue

1. see video
2.
3.
...

### What version of Home Assistant Core has the issue?

 2022.2.0.dev20220101

### What was the last working version of Home Assistant Core?

dk

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

MacOS 12.0.1 Monterey 12.0.1 

### State of relevant entities

na

### Problem-relevant frontend configuration

na

### Javascript errors shown in your browser console/inspector

Nothing in the log

### Additional information

speaks for itself

**Comment by garry0garry** [comment]
2021.12.9 - not fixed

**Comment by Mariusthvdb** [comment]
I still see it in dev20220112.
In all diagnostic panels, and some configuration panels. But also in the main panels like:

<img width="1054" alt="Schermafbeelding 2022-01-13 om 10 36 38" src="https://user-images.githubusercontent.com/33354141/149304524-a2436ab1-41c4-4c0d-8877-d3ab6faddc27.png">

(the previously noticed disappearing effect has gone, they are invisible on click.)

**Comment by ildar170975** [comment]
Same as https://github.com/home-assistant/frontend/issues/10903

**Comment by garry0garry** [comment]
2021.12.10 - not fixed

**Comment by garry0garry** [comment]
![изображение](https://user-images.githubusercontent.com/95581374/149882995-41d47377-e82d-4058-820f-cc3179e78818.png)

**Comment by spacegaier** [comment]
> 2021.12.10 - not fixed

Yes, but it is already fixed in the dev version, so it will be part of the next major version 2022.2.

**Comment by Mariusthvdb** [comment]
still seeing this in today's dev  2022.2.0.dev20220118

<img width="666" alt="Schermafbeelding 2022-01-18 om 11 43 04" src="https://user-images.githubusercontent.com/33354141/149922319-499ce6f9-801a-44b9-94d2-83ca718320ca.png">
