### ISSUE TITLE
Changing default dashboard hides original default dashboard

### ISSUE THREAD

**Issue by jamesmyatt** [home-assistant/frontend#11069]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I change the default dashboard configuration, the original default dashboard ("overview" or whatever) is not accessible in the sidebar.

I first noticed this in the Android companion app, but have reproduced it on Chrome for Windows and Firefox for Windows.

### Describe the behavior you expected

Default dashboard should remain in sidebar when not set as default.

### Steps to reproduce the issue

1. Change "default dashboard"
2. Observe that "Overview" is missing from sidebar

### What version of Home Assistant Core has the issue?

core-2021.12.7

### In which browser are you experiencing the issue with?

Firefox 95.0.2 (64-bit)

### Which operating system are you using to run this browser?

Windows 10 Pro

### Additional information

Originally raised on android repo: https://github.com/home-assistant/android/issues/2082

**Comment by stephenhouser** [comment]
+1

**Comment by Salamandar** [comment]
Can confirm. This is an anti-feature.

There are 2 use cases here : 

* Always hide "Overview" on every device (you should select another as the default on every device) -> This could be the case because you don't like the "Overview" name or icon.

* Never hide "Overview" even if you selected a default one, because you still access to see it sometimes, even if you selected another one as the default on the device -> This can be the case on phones (if you built a phone-friendly UI).

**Comment by zachberger** [comment]
+1 to this. On my phone I always want a custom built dashboard to appear by default, but when I want to do something more advanced I want the autogenerated "Overview" dashboard.

**Comment by Salamandar** [comment]
This is still relevant.

**Comment by stephenhouser** [comment]
+1

**Comment by hugalafutro** [comment]
I'm also running into this issue, although only on Android app. I originally reported it at https://community.home-assistant.io/t/overview-tab-disappears-when-default-dashboard-is-selected/506543/7 where I was told android app does not control the behaviour and to report it here which is how I found this issue. 

Unlike the OP I retain access to Overview tab on PC even with custom default dashboard, however the behaviour is reversed on Android.

**Comment by pklijzing** [comment]
Same here on Android, iOS and iPadOS.

**Comment by Znegl** [comment]
The worlds easiest fix: Just add a new dashboard. Any new dashboard will function like the original default dashboard until changed — it's just not documented anywhere (at least not anywhere I could find).

**Comment by hugalafutro** [comment]
> The worlds easiest fix: Just add a new dashboard. Any new dashboard will function like the original default dashboard until changed — it's just not documented anywhere (at least not anywhere I could find).

I'm sorry but I don't understand. The whole issue is about when you add a new dashboard the Overview disappears. How is adding another dashboard supposed to fix it?

**Comment by Znegl** [comment]
@hugalafutro Any new dashboard will automatically be filled with the same content as the original default dashboard and will update automatically.

**Comment by hugalafutro** [comment]
@Znegl Sorry for being thick before I got it now, this should really be better documented, You were right I just added blank dashboard, didn't put anything in it and it autofilled with everything the Overview tab normally has.

**Comment by Znegl** [comment]
@hugalafutro I felt the same way when I discovered the workaround 😅

**Comment by marcelodavanzo** [comment]
While the workaround helps it's not a long term fix for the bug.

With this workaround you end up with the original Overview tab + the empty dashboard (that replicates the contents of the Overview tab) on every device where the bug that hides the Overview tab is present.

**Comment by hugalafutro** [comment]
> While the workaround helps it's not a long term fix for the bug.
> 
> With this workaround you end up with the original Overview tab + the empty dashboard (that replicates the contents of the Overview tab) on every device where the bug that hides the Overview tab is present.

You can hide the default dashboard by clicking your user picture then selecting "Change the order and hide items from the sidebar" You can also press and hold the header of the sidebar to activate edit mode.

Then even though the Settings / Dashboard you will see 2 Overviews, on the sidebar you only will see the one you want.
on PC:
![image](https://user-images.githubusercontent.com/30209689/224527149-f9036d52-0181-4ec6-b8a1-8e7f7ce0fbe7.png)

**Comment by marcelodavanzo** [comment]
> You can hide the default dashboard by clicking your user picture then selecting "Change the order and hide items from the sidebar" You can also press and hold the header of the sidebar to activate edit mode.

Sure, that works for one device but needs to be done for every other device you use and will reset if the frontend cache is every reset as well. I understand it's a short term fix, but still a lot of steps just to get around a bug.

**Comment by bmcclure** [comment]
I think the underlying issue with how this works, which the workaround does not solve, is that there is no way to either always hide Overview or always show Overview, like you can do with every other dashboard.

Yes, you can create a separate dashboard to replace Overview, but every device will then start off with duplicate Overview dashboards until they choose something else as a default.

I can't think of a great reason for Overview to have special handling like it does now--why would someone want it to become inaccessible just because they want the default dashboard to be a different one? Those are two separate concerns that should be separate options.

**Comment by ironbiff** [comment]
+1

just trying to push this. I do not understand why this bug (or maybe misunderstood feature) is over 1 year old

**Comment by Harmanii** [comment]
+1

I did find a cumbersome workaround: On any dashboard > Menu > Edit Dashboard > Menu > Manage Dashboards > Open the Overview dashboard by clicking the pop-out button.

**Comment by jasongabler** [comment]
+1 Still happening.

**Comment by fire-burner** [comment]
First of all, I would like to thank every developer for this great piece of software!

Until now, I was not aware, that the Overview Dashboard is any different than any other Dashboard. Probably because right at the beginning when I started with HA earlier this year, I had removed the default content and modified it to my standard Dashboard for the computer.
Then recently I had created a separate one for my phone and made it default on the phone. Just I today I realized, the default Overview was missing and then I tried to figure out what was going on until I found this issue.

> @hugalafutro Any new dashboard will automatically be filled with the same content as the original default dashboard and will update automatically.
This workaround doesn't help in my case at all, because I have a modified Overview. So I probably will clone my overview and make it the default on the PC instead.

To solve this, I see two options, either document this feature the way that beginners will not run into the same mistake as I  or one should be able to decide themselves if they want to hide Overview or not. The latter would be my preferred solution.

**Comment by pjdubya** [comment]
While I'm sure folks are trying to be helpful in suggesting other workarounds, I don't think they're appropriate at this point given that there's an actual bug here that needs attention, not more workarounds. Has anyone looked at the code yet to try to fix it? I can't imagine it's a complex problem to address correctly.

**Comment by bmcclure** [comment]
It's not totally clear to me that this is truly a bug. I want it changed too, but are you saying there's something indicating that this feature is supposed to work differently but is broken?

I'm more inclined to think it's just how the feature was developed, but that it's not very useful as-is and should be rethought to be more consistent and useful.

I'm grateful for people providing the workarounds, but I do agree that this should ultimately be addressed in the core code, whether it's truly a bug or not.

It would be a fundamental change in how the dashboards work, causing everyone who already has come to expect the current functionality to have to "fix" their dashboards if they don't want the overview to appear. Not a big deal IMO, but I still think it's worth considering that this "bug" might be used as a feature by some people currently. Again, I'm still for changing the behavior, I can't see any good reason for Overview to have special handling, it should be treated like any other dashboard, but I just think it extends a little beyond a bug fix.

**Comment by NuttCorp** [comment]
+1

**Comment by carefulcomputer** [comment]
+1

**Comment by carefulcomputer** [comment]
Current behavior basically takes away the overview dashboard as soon as you start using a new dashboard. I do not think that is very intuitive or user friendly. Several users use multiple dashboards. I created a new dashboard for my mobile (doesn't have all fancy charts and just quick control buttons) but I also want to be able to switch to full version when needed. The 'overview' dashboard disappeared as soon as I switch to my mobile dashboard.

For folks who end up searching for this issue and end up on this thread , here is what I did -
1. Create a new empty dashboard (to use instead of your 'overview' dashboard).
2. Go to current overview dashboard, copy raw config (use top right 3 dots)
3. Paste the raw config into new empty dashboard's raw config (using same top right 3 dots)
4. Modify 'Title' and 'path' to your new dashboard's name (e.g. 'Desktop')
5. Save
6. Go to settings->dashboard on each of your device and pick the appropriate dashboard.

Here are downsides of this approach
Either you will  have to select a dashboard on every new device you use or you need to make sure your 'overview' dashboard and your 'primary' dashboard are always in sync.

**Comment by jamesmyatt** [comment]
This is definitely a bug since it's so unexpected and causes different behaviour on different devices. Even though it's not a showstopper, it really needs to be fixed. If it's a feature, then there needs to be a way of turning it off.

I doubt that anyone is relying on this "feature", since it only affects devices where the default dashboard has been changed. Working around it is a major pain, with broken urls etc and different behaviour on different devices. So I suspect that the vast majority of people have either accepted that they _can't_ change the default dashboard (as I have) and are just shoving more cards on to the Overview page, or are using wall tablets, which are set to a single dashboard anyway.

**Comment by poohbah** [comment]
+1

My own path to find this bug - I built a simplified dashboard for my wife to use as the default on her android phone. This seems like a common thing to do. Once that new dashboard was set to the default on her phone the main "overview" dashboard is gone and cannot be selected at all. I confirmed this on my own phone. Very weird behavior. Why would the main dashboard be unavailable just because I selected another dashboard as the default?

**Comment by WolfeCub** [comment]
I investigated this a little bit this line: https://github.com/home-assistant/frontend/blob/dev/src/components/ha-sidebar.ts#L164 seems to be the source of this issue. If we look at what the values are 
![image](https://github.com/home-assistant/frontend/assets/1369773/7b31a16e-8f47-42cb-a237-22c5ee8ae9f6)
the default overview dashboard doesn't have a title. So when it's not the default dashboard that line will filter it out.

Via the UI there doesn't seem to be a simple way to set the title of the overview dashboard but it would be nice if there was some way.

**Comment by stanwebber** [comment]
this is still a bug on 2024.5.5 with 2024.4.1 android client.

**Comment by evilDave** [comment]
+1
On the mac two of the workarounds don't really work: ordering the sidebar does not change which dashboard is shown when the app opens (the whole point of changing the default was to see my custom on first, but leave the autogenerated one available), and creating a blank dashboard does not get filled with the contents of the overview, it's just blank... The other workaround, copying the overview into a new dashboard will "work" however that new dashboard will not now automatically stay up to date with new devices etc - which for me is the entire benefit of the overview.
RE the code mentioned above that checks the title: are there other untitled panels that this code was created to hide? Perhaps (if there is friction to changing this feature because its "supposed to be like that" for some reason) a way to keep the current "default" behaviour is just to provide a button somewhere (manage dashboards pane?) to "show overview when it's not the default" that can just add a title to the overview panel.

**Comment by holocronweaver** [comment]
Still occurs in Core 2024.9.3, Frontend 20240710.0.

**Comment by benslice** [comment]
+1

**Comment by curuvar** [comment]
I'm having this issue on MacOS (Both on the Safari and Brave browsers).  The dashboard is still present (I can get to it via Settings -> Dashboard), but it does not show in the sidebar.

**Comment by bowesmana** [comment]
Came across this yesterday as I have a simple dashboard for mobile/wall tablet and want those as defaults, but also need access to the "everything" dashboard. Can't fathom why you'd lose it, but now this is shown when you click on the Overview dashboard in Settings->Dashboards

**The default dashboard, Overview, cannot be edited from the UI. You can hide it by setting another dashboard as default.**

even if this were the case, it should be possible to put it back.

Adding a new empty dashboard does not work if it once did - 2024.11.3 just leaves that dashboard empty.

Would be great if devs could just allow it to be visible to be added back on Android (other?) devices

**Comment by stanwebber** [comment]
my workaround: i have a default dashboard configured when connected to my home network (behind enterprise nat). when away from home i have a reverse ssh tunnel (via autossh) to an external host open to internet connections thru a dynamic dns name. when my client recognizes it is connected externally the overview dashboard is again available without having to reconfigure anything. when at home i can just temporarily disable my wifi for the same effect.

**Comment by schraller** [comment]
Verry irritated by this issue - thought I did something stupid when I suddenly could not find the default Dashboard on my Android Device. The suggested Workaround with an empty Dashboard does not work anymore on the current Version.

I now have two poor options: Keep the huge and crowded "Overview" Dashboard as a default on mobile - which means every time I have to first choose another dashboard to see the things I really want to see. Or set another Dashboard as default an loose the option to quickly check the status of some special entity that is not on any of my custom dashboards.

**Comment by WalterWolf49** [comment]
Nearly 3 years later and this very weird and inconvenient bug has not yet been fixed. Very unfortunate.

**Comment by I-Would-Like-To-Report-A-Bug-Please** [comment]
Wow, Just stumbled across the problem as well after a little bit of google and searching...

**Comment by stephenhouser** [comment]
No longer considered a bug? Some explanation would be helpful.

**Comment by pjdubya** [comment]
@karwots the bug label should be restored. Even if this is by design it's a terrible design that makes no UX sense and should be fixed.

**Comment by jcsp101** [comment]
this is still an issue and seems like a bug given it does not happen on PC

**Comment by TilmanGuenther** [comment]
I have also encountered this bug.

**Comment by pjdubya** [comment]
This issue is still present in current builds 
 
 
  On Mon, Jul 28, 2025 at 5:02 PM, ***@***.***> wrote:   github-actions[bot] left a comment (home-assistant/frontend#11069)
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.
Please make sure to update to the latest Home Assistant version and check if that solves the issue. Let us know if that works for you by adding a comment 👍
This issue has now been marked as stale and will be closed if no further activity occurs. Thank you for your contributions.

**Comment by I-Would-Like-To-Report-A-Bug-Please** [comment]
Agreed, still an issue. It would be awesome if fixed.

**Comment by jt6186** [comment]
This is weird an annoying, however this workaround is not that bad:  settings->dashboards->overview hit the arrow box and it jumps to the overview dashboard.  I only really want overview when I'm testing/debugging something so the extra steps over having it in the side panel is doable.

**Comment by lukeol11** [comment]
> This is weird an annoying, however this workaround is not that bad:  settings->dashboards->overview hit the arrow box and it jumps to the overview dashboard.  I only really want overview when I'm testing/debugging something so the extra steps over having it in the side panel is doable.

Alternatively you can add a tag or similar on your new chosen default dashboard and set the action to navigate to Overview and set visibility to Mobile devices only

**Comment by zhudhjen** [comment]
+1

With recent updates of My Home dashboard and Rooms dashboard, I really want to update my default dashboard to those, especially on mobile, since they are very handy. Then I encounter this bug, because I still want to use some customized features from my previous overview dashboard.  This has been very frustrating.

Devs, if you really want people to try out the fancy new dashboards, this has to be fixed. Otherwise, more people will land here at this bug, and even more will silently give up the new dashboards.

**Comment by hukm** [comment]
+1

**Comment by el-bakkali** [comment]
+1

Updating to 2026.1

home is not visible and has never been in sidebar

i only have overview

Although in dashboard it states that home is a built in 

<img width="1917" height="521" alt="Image" src="https://github.com/user-attachments/assets/62cfb573-6812-441e-9bec-ee292ad7e0cb" />

**Comment by amomchilov** [comment]
@el-bakkali That one is hidden by default. You can custom the sidebar for your user on the [user profile page](https://my.home-assistant.io/redirect/profile/).

<img width="400" alt="Image" src="https://github.com/user-attachments/assets/1ca47c4c-f8a9-4e61-a330-9b648a89044a" />

<img width="300" alt="Image" src="https://github.com/user-attachments/assets/37befe64-91ef-4ef3-a476-9dc4d51de2ef" />

**Comment by karwosts** [comment]
I think this is not an issue anymore. Overview is still a visible dashboard no matter which dashboard is set as default.

**Comment by stanwebber** [comment]
overview is not a visible dashboard for me.

Installation method - Home Assistant OS
Core - 2026.1.2
Supervisor - 2026.01.1
Operating System - 17.0
Frontend - 20260107.2
Companion app - 2025.11.4-full (19134)

**Comment by karwosts** [comment]
Is it hidden in your user settings?

<img width="1537" height="691" alt="Image" src="https://github.com/user-attachments/assets/3c090dd6-6c8b-4ebe-a6b8-2c4402ba3435" />

**Comment by stanwebber** [comment]
what you have circled in green is not visible in my android client when i have the default dashboard set to a user created one under per user settings. overview is only visible in the side pane if it is set as the default dashboard.

**Comment by karwosts** [comment]
Go to user profile settings, find and select "Change the order and hide items from the sidebar", and check if you have Overview there toggled off/disabled.

**Comment by jamesmyatt** [comment]
I think this is not an issue any more. Thanks

**Comment by stanwebber** [comment]
yeah, overview was hidden. i guess i've fallen behind on the features added to the client. this is a non-issue for me now.
