### ISSUE TITLE
Map now shows geocoded location sensor while device_tracker is also there

### ISSUE THREAD

**Issue by hmmbob** [home-assistant/frontend#11970]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Since the latest HA Companion app upgrade (latest beta), a new device shows in the Home Assistant frontend map pane. This is duplicate information, as the `person` entity linked to this `device_tracker` _also_ shows in the map. I actually don't see the added value of the `geocoded location sensor` showing in the map, as one cannot attach it to a person (`person` only allows `device_tracker` devices) and it now duplicates information. 

![image](https://user-images.githubusercontent.com/33529490/157061915-4e5db090-d1e5-4296-89fb-3cf70cc39683.png)
Same device, twice on the map

Furthermore, the sensor also isn't hidden in the home zone:
![image](https://user-images.githubusercontent.com/33529490/157061454-4c8c9a79-b86a-4e9a-9d3e-c5fadc8640d7.png)

### Describe the behavior you expected

A tracked device should only show once on the map, and if the tracked device is attached to a person, only the person entity should show.

### Steps to reproduce the issue

1. Upgrade to latest beta (android in this case) HA companion app
2. Make sure to enable both `device_tracker` and `sensor.geocoded_location`
3. Observe built-in map panel

### What version of Home Assistant Core has the issue?

core-2022.3.1

### What was the last working version of Home Assistant Core?

n/a

### In which browser are you experiencing the issue with?

Chrome + HA app

### Which operating system are you using to run this browser?

all

### State of relevant entities

![image](https://user-images.githubusercontent.com/33529490/157070565-41d50dfd-749f-4b8e-9ef6-e80a44e77839.png)
(No worries, used fake GPS)

### Additional information

Caused by https://github.com/home-assistant/android/pull/2341
Initial issue in Android repo: https://github.com/home-assistant/android/issues/2348

**Comment by dshokouhi** [comment]
To add to this issue, the docs for the map panel clearly state it should only show device trackers.

https://www.home-assistant.io/integrations/map/

```
This offers a map on the frontend to display the location of tracked devices. To set up tracked devices, look at the [device tracker](https://www.home-assistant.io/integrations/device_tracker/) documentation.
```

**Comment by SlyFoxeh** [comment]
Same here.... But on the latest Home Assistant 2022.3.2:
- Pixel 3A android 12 does have Sensor Geocoded Location and updates on the map
- Huawei 7C Android 9 - Doesn't have geocoded location, only tracker sensor and stuck on the map in the one place and dont move
- Huawei P Smart Z Android 10 - Deosnt have geocoded location, only tracker sensor and doesnt show on the map at all

**Comment by hmmbob** [comment]
It's based on the HA app version you run, it's only an issue with latest beta (at least for Android)

**Comment by SlyFoxeh** [comment]
> It's based on the HA app version you run, it's only an issue with latest beta (at least for Android)

Latest Beta of HA phone app only on pixel 3a, on the Huawei 7C and Huawei P Smart Z installed latest public release, but now was downgrade to rhe public on the pixel 3a and still P Smart Z doesnt appear on the map, Huawei 7C stuck on the previous geo location

**Comment by hmmbob** [comment]
looks like a different issue, please open a new one

**Comment by hmmbob** [comment]
Yeah, apparently this feature made it to the stable Android app (no longer beta only), because all other tracked devices in our house now also show this behavior. A lot of duplicate icons on the map now 😢

**Comment by SgtBatten** [comment]
I think the functionality is actually in HA core and the Android app update fixed a compatibility that was previously broken, this revealing this issue.

**Comment by hmmbob** [comment]
> I think the functionality is actually in HA core and the Android app update fixed a compatibility that was previously broken, this revealing this issue.

No, it is a frontend issue. The core component `map` is very limited:

https://github.com/home-assistant/core/blob/dev/homeassistant/components/map/__init__.py

**Comment by engeles20** [comment]
Any update on this?

**Comment by AdmiralStipe** [comment]
Still no news? It's a pretty anoying issue (well, at least for me).

**Comment by GrayJackal** [comment]
Also having this issue, SGL device appeared on my map and won't go away, annoying since it doesn't even disappear when I'm home

**Comment by ghluhi** [comment]
I can confirm this is still an issue in 2022.5.0.

**Comment by rayfoster14** [comment]
I have had the same issue since March also. I have been using a workaround fix for the time being which works pretty well.
A separate dashboard with the map card in panel mode looks convincingly similar to the regular map dashboard.

Here is my Map Dashboard YAML
`views:
  - theme: Backend-selected
    title: Map
    type: panel
    badges: []
    cards:
      - type: map
        entities:
          - entity: person.person1
          - entity: person.person2
          - entity: zone.home
        default_zoom: 17
`

Whilst this does not 'fix' the issue with the default maps, it does offer a convincing look-alike (with arguably more features!)

**Comment by Mr-Groch** [comment]
Still an issue in 2022.6.0

**Comment by sanderlv** [comment]
Stumbled on this as well... how to change this annoying behavior?

**Comment by AdmiralStipe** [comment]
Are we all being actively ignored here?

**Comment by dshokouhi** [comment]
Just wanted to give everyone an update here. The android app will be moving away from having `latitude` and `longitude` as attributes of the geocoded sensor after the above linked PR is merged. We will be combining the attributes into `location` just like iOS so that will solve this issue.

**Comment by hmmbob** [comment]
Great, thanks!

**Comment by dshokouhi** [comment]
> Is there any progress on this?

My comment just above yours was 5 days ago, I think we can have some patience while we wait for the PR to be merged.

**Comment by sanderlv** [comment]
Sorry, I did not realize that this would solve the issue on the map version in the browser as well. I have interpreted it as it was only for the companion app.

**Comment by dshokouhi** [comment]
The issue is with the data from the sensor provided by the Android app which causes it to show up in the maps. It can only be fixed in the Android app.

**Comment by heso** [comment]
![photo_2022-08-30_16-10-29](https://user-images.githubusercontent.com/6051720/187422019-0ac8e60b-7aed-4d34-b3cd-3487c8e2e96e.jpg)
hola, after updating app to 2022.8 device_tracker still not equal to geocoded_location..It feels like it froze my home coordinates and doesnt want to change to actual ones. (Android, Samsung)

**Comment by dshokouhi** [comment]
This is actually fixed in the latest beta and not in 2022.08. Will be in the next release of the Android app the beta will be in the play store Saturday night pending review from Google.

**Comment by dshokouhi** [comment]
Fixed via https://github.com/home-assistant/android/pull/2809

**Comment by dshokouhi** [comment]
Closing as this has been rolled out to all users.
