### ISSUE TITLE
Blueprint boolean input is not retaining true/false selection through the Automation edit

### ISSUE THREAD

**Issue by elementzonline** [home-assistant/frontend#12542]
### The problem

I have adapted a Blueprint from the HA forum to adapt my usecase of selecting weekdays to schedule thermostat between given time to set its temperature and HVAC mode. 

I am using the following blueprint in the blueprints folder. 

[See the gist for the Blueprint I am using by clicking here ](https://gist.github.com/elementzonline/82225b7376e714980180f6f38b409cd3)

I am able to make automation from the Blueprint. While creating the blueprint, the weekdays can be selected, and the automation works as expected. But after that if I edit the automation and change the weekdays which I initially configured, its not getting saved. I am using Boolean selector for each day selection for the scheduling of the thermostat. 

![Issue video: Screenrecord](https://user-images.githubusercontent.com/2993183/166133613-c8628651-46ec-41d1-8e1a-0183ce0b55c3.gif)

I am also attaching a screen record, which may help the experts to quickly view the issue I am facing. 

Thanks,
Dhanish 

### What version of Home Assistant Core has the issue?

2022.4.7

### What type of installation are you running?

Home Assistant Core

### Integration causing the issue

Blueprint

### Example YAML snippet

```yaml
blueprint:
  name: Schedule a thermostat
  description: Schedule your thermostat to automatically set mode between chosen time interval on selected day.
  domain: automation
  input:
    thermostat_entity:
      name: Thermostat
      description: The thermostat for scheduling.
      selector:
        entity:
          domain: climate
    target_mode:
      name: Target Mode
      description: Input the target mode to apply during the schedule. (Off mode will be set at the end of the schedule)
      default: heat
      selector:
        select:
          options:
            - heat
            - cool
    target_temperature:
      name: Target Temperature
      description: Input the target temperature to apply during the schedule
      default: 20.0
      selector:
        number:
          min: 0.0
          max: 60.0
          step: 0.1
          mode: slider
    start_time:
      name: Start Time
      description: Start Time of the day to activate the schedule
      selector:
        time:
    end_time:
      name: End Time
      description: End Time of the day to stop the schedule (Off mode will be set at the end of the schedule)
      selector:
        time:
    run_on_sunday:
      name: Run on Sunday
      description: Should this action run on Sundays
      default: true
      selector:
        boolean:
    run_on_monday:
      name: Run on Monday
      description: Should this action run on Mondays
      default: true
      selector:
        boolean:
    run_on_tuesday:
      name: Run on Tuesday
      description: Should this action run on Tuesdays
      default: true
      selector:
        boolean:
    run_on_wednesday:
      name: Run on Wednesday
      description: Should this action run on Wednesdays
      default: true
      selector:
        boolean:
    run_on_thursday:
      name: Run on Thursday
      description: Should this action run on Thursdays
      default: true
      selector:
        boolean:
    run_on_friday:
      name: Run on Friday
      description: Should this action run on Fridays
      default: true
      selector:
        boolean:
    run_on_saturday:
      name: Run on Saturday
      description: Should this action run on Saturdays
      default: true
      selector:
        boolean:



variables:
  weekly_schedule:
    - !input 'run_on_monday'
    - !input 'run_on_tuesday'
    - !input 'run_on_wednesday'
    - !input 'run_on_thursday'
    - !input 'run_on_friday'
    - !input 'run_on_saturday'
    - !input 'run_on_sunday'

trigger:
- at: !input start_time
  platform: time
  id: "start_trigger"
- at: !input end_time
  platform: time
  id: "end_trigger"

condition:
  - condition: template
    value_template: '{{ weekly_schedule[now().weekday()] }}'

action:
- choose:
  # Run for start time
  - conditions:
    - condition: trigger
      id: start_trigger
    sequence:
    - service: climate.set_temperature
      data:
        temperature: !input target_temperature
      target:
        entity_id: !input thermostat_entity
    - service: climate.set_hvac_mode
      data:
        hvac_mode: !input target_mode
      target:
        entity_id: !input thermostat_entity
  # Run for end time
  - conditions:
    - condition: trigger
      id: end_trigger
    sequence:
    - service: climate.set_hvac_mode
      data:
        hvac_mode: 'off'
      target:
        entity_id: !input thermostat_entity
  default: []
mode: single
```

### Additional information

I am using HA core through a virtual environment. 
Following is my system configurartion.

```
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

```

**Comment by frenck** [comment]
Transferred this issue to the frontend, as this is frontend-related issue.

**Comment by elementzonline** [comment]
> Remove `default: true` from each Input Boolean selector.

Tried that already. No luck with it.

**Comment by tdejneka** [comment]
> No luck with it.

OK, that's too bad. It was offered in the hope of serving as a temporary workaround to the bug (because it really should respect the automation's settings). Hopefully it's an easy fix.

**Comment by Nalith** [comment]
Do we have any update on this, as I am getting this exact same issue and its driving me up the wall? What I have figured out is it seems to save the value when changed to True but not when changed to False.

**Comment by jeanaaaa** [comment]
Same issue.
When switching the boolean in the automation (built by the blueprint), doesn't enable the [Save] button.
Seems the boolean modification in the automation is completely ignored ...  we can see it in the animation of the first post.

**Comment by crkochan** [comment]
I've also run into this.

Seems to be related to #12657.

**Comment by zsarnett** [comment]
Fixed in https://github.com/home-assistant/frontend/pull/13173

**Comment by schiz0phr3ne** [comment]
Still not working here.

 Home Assistant 2022.7.5
Supervisor 2022.07.0
Operating System 8.2
Interface utilisateur : 20220707.1 - latest

**Comment by erkr** [comment]
> Still not working here.
> 
> Home Assistant 2022.7.5
> 

It was delivered to dev6. So I guess it will be part of core 2022.7.6
Really looking forward for this fix as well!
