### ISSUE TITLE
Logbook calendar not using locale for week or names

### ISSUE THREAD

**Issue by TimoJJ** [home-assistant/frontend#13789]
### The problem

Logbook calendar is not using set system locale for week start-end  days and day and month names. I use English-GB and this should use Monday as start of the week but it still uses Sunday. And if I use Finnish (Suomi) as language, calendar portion is not translated, it's still in English and uses Sunday as week start day. Also left side button for 'This Week' selects days from Sun to Sat.
.
![image](https://user-images.githubusercontent.com/63199895/189471101-fd497d92-2a5e-4454-a88c-f0bb95dc0f25.png)

### What version of Home Assistant Core has the issue?

2022.9.1

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Logbook

**Comment by frenck** [comment]
Moved this issue to the frontend issue tracker, as this is an frontend and not backend issue.

**Comment by KennyHec** [comment]
same problem here

**Comment by m4v3r1ckNl** [comment]
Thanks @TimoJJ for filing this as an issue.

The preferred language should be an independent setting apart from the "locale" and so also the start day of the week. I live in The Netherlands, am bi-lingual but always use my UI - not only HA - in English.
- Monday as start of the week (Dutch)
- Language set to English

**Comment by koopernick** [comment]
Any update on this issue ? Anyone looking into it ?

**Comment by karwosts** [comment]
This should have been fixed back around the end of last year. 

https://github.com/home-assistant/frontend/pull/13991

Have you set your preferred date in your user profile?

**Comment by poudenes** [comment]
Not solved and only the United States, Canada, most of South America, China, Japan and the Philippines officially consider Sunday to start the week ahead. So would be more then normal that we have Monday as start of the week instead using Sunday because of those short list countries.

**Comment by BebeMischa** [comment]
It is solved back then for me, in the Netherlands. Just for reference...

**Comment by Instigater** [comment]
I can confirm that now it can be tuned to user's preferences in settings of user profile.
