### ISSUE TITLE
Lost draggable dot on thermostats

### ISSUE THREAD

**Issue by krzysztofsk** [home-assistant/frontend#15662]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Can't change temperature on thermostat card. Dot is missing.
<img width="409" alt="Zrzut ekranu 2023-03-1 o 21 36 53" src="https://user-images.githubusercontent.com/15669227/222269968-b047670d-c8bb-4c06-8242-f5852eaf8635.png">

### Describe the behavior you expected

Thermostat dot should be visible and draggable.

### Steps to reproduce the issue

1. Use thermostat card

### What version of Home Assistant Core has the issue?

2023.3.0

### What was the last working version of Home Assistant Core?

2023.2.5

### In which browser are you experiencing the issue with?

Chrome, HA companion app Android

### Which operating system are you using to run this browser?

MacOS Ventura 13.2.1

**Comment by ChristophCaina** [comment]
+1 chrome, Windows 10 and I can confirm the error in the logs
```
Logger: frontend.js.latest.202303010
Source: components/system_log/__init__.py:254
First occurred: 00:09:08 (8 occurrences)
Last logged: 00:30:18

https://home.caina.family/frontend_latest/eb71732c.js:2:25186 Uncaught TypeError: Cannot read properties of null (reading 'classList')
```

**Comment by karwosts** [comment]
My core/development install doesn't exhibit this (fetched frontend:master and core:master), but my normal HAOS install does.

**Comment by balloob** [comment]
99% sure this is because of HTML minifying. CC @steverep

**Comment by steverep** [comment]
Yeah probably. I'll check it out.

**Comment by steverep** [comment]
Does this seem to be a problem on all `<round-slider>` elements or just thermostat?

**Comment by karwosts** [comment]
Light card is also missing. 

![image](https://user-images.githubusercontent.com/32912880/222315540-fb8cfcd6-57db-41b9-bdec-34f70a7c0508.png)

**Comment by 3ative** [comment]
In case it's relevant, the "Dots" are also missing on an ESPHome Thermostat too
![image](https://user-images.githubusercontent.com/51385971/222318412-fcf1b04f-1f26-4480-9b71-aa0a33242462.png)

**Comment by steverep** [comment]
I think this has to do with SVG minification but when I examine the minified code, nothing is jumping out as wrong.

@karwosts can you confirm the visual problem appears in development if you change line 116 of `bundle.js` to:

```js
    /* isProdBuild && */ [
```

This will enable minification temporarily for development.

**Comment by karwosts** [comment]
> @karwosts can you confirm the visual problem appears in development if you change line 116 of `bundle.js` to:
> 
> ```js
>     /* isProdBuild && */ [
> ```
> 
> This will enable minification temporarily for development.

Yes, I confirm that. Once I added that comment, it broke my dev instance the same as the production one.

**Comment by steverep** [comment]
Thanks for the quick reply.  I fixed it.  PR is coming.

**Comment by steverep** [comment]
I just lined a PR.  If you want to double-check the fix, make sure to add that comment again.

**Comment by pedromfa** [comment]
Same issue here with the thermostat... Any fix?

**Comment by jenshenk** [comment]
Great news, I was already afraid I need to cope with this for a couple of weeks after updating to 3.0 only for the yellow lights :)

**Comment by artblue1** [comment]
fixed with 2023.3.1

**Comment by jenshenk** [comment]
Amazing, thanks so much!

**Comment by MrPresident2** [comment]
Hey, the problem did not solve with 2023.3.1. I'm still missing the dot. any updates about this problem?

**Comment by KoalaBear84** [comment]
Here it did solve the issue. Could you try, if on desktop, CTRL + F5, or clear cache?

**Comment by GeorgeRT** [comment]
Did a Quick Reload to effect fix.  Thanks.
