### ISSUE TITLE
Calendar card loses it's styling

### ISSUE THREAD

**Issue by envy** [home-assistant/frontend#16848]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have a dashbboard with multiple views and a calendar card on the first main view, it looks like this:

![grafik](https://github.com/home-assistant/frontend/assets/241552/b87f8894-7d79-4310-b9db-87502610e8af)

When I click on a different view and then come back to the previous view, it looks like this:

![grafik](https://github.com/home-assistant/frontend/assets/241552/f6622db5-9f7e-418f-80d4-7806bdff8039)

The same happens when trying to edit the dashboard, the card just loses its styling.

### Describe the behavior you expected

The calendar card should keep its styling

### Steps to reproduce the issue

1. Put a calender card on the first view on the default dashboard, make sure it has entries.
2. Refresh site
3. Calendar card should look ok
4. Switch to edit mode
5. Calendar card shoul look wrong.
...

### What version of Home Assistant Core has the issue?

2023.06.1

### What was the last working version of Home Assistant Core?

2023.05.x

### In which browser are you experiencing the issue with?

Firefox 113.0.1 (also tested Edge 114)

### Which operating system are you using to run this browser?

Windows 11

### Problem-relevant frontend configuration

```yaml
type: calendar
entities:
  - calendar.alw
initial_view: listWeek
title: Mülltonnen
```

**Comment by illascanbe** [comment]
I'm also experiencing this behaviour since the update to 2023.06.x

![image](https://github.com/home-assistant/frontend/assets/121318283/b4defcc9-921d-4700-a0a3-ec9c4d383f74)

**Comment by eeFLis** [comment]
same here.

Can also be reproduced in my case by minimising the siedbar and enlarging it again.
If you then switch between the calendar views, the calendar loses its style.

**Comment by Canonfodda** [comment]
Also seeing this issue with Calendar card. Have tested it on Firefox, Google, Safari web browsers. 
Running RPI 3B+ 
Home Assistant 2023.6.2
Supervisor 2023.06.2
Operating System 10.2
Frontend 20230608.0 - latest
also was seen on 2023.6.1 
Can also reproduce styling fubar using the above examples, and also moving between Lovelace tabs. 
No errors being seen in ha su log, or other logs. 
Have remove, cleared cache and re-installed card, but same issue.

**Comment by matthias1189** [comment]
Same here for me

**Comment by Manticore-007** [comment]
I also have this issue, I was playing around with card-mod and thought there was an issue with that, later I found out it also gives this issue without card-mod. Issue restores with a refresh, but reappears after clicking another page and going back.

**Comment by Smokey01966** [comment]
Same issue

When dashboard loads the first time everything is fine but putting the calendar card in a conditional card and then hiding and showing the cards causes everything to break. When in month view it breaks so bad the page freezes.

Base code for testing (need a calendar called test and an input boolean called test)

```
views:
  - type: panel
    title: Calendar Display
    path: calendar-display
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: entity
            entity: input_boolean.test
          - type: conditional
            conditions:
              - entity: input_boolean.test
                state: 'on'
            card:
              initial_view: listWeek
              type: calendar
              entities:
                - calendar.test 
```

**Comment by mamoel666** [comment]
Add me to the list.

In my case the issue occurs when switching between tabs in a dashboard, but not when switching between different dashboards.

**Comment by envy** [comment]
This is still happening on 2023.07.1, Frontend 20230705.1 - latest

**Comment by mamoel666** [comment]
Workaround: I now use [Atomic Calendar Revive](https://github.com/totaldebug/atomic-calendar-revive)

**Comment by youngnapoleon** [comment]
Can confirm this is happening with 2023.07.3 as well.

**Comment by Andurilll** [comment]
I also have exactly the Same Problem. Hit me up if you need infos to solve it.

**Comment by envy** [comment]
This is still happening with 2023.08.1

**Comment by anderl1969** [comment]
Same problem here with 2023.08.4 
Tested with Chrome, Firefox and Edge

**Comment by kristjanhaukur** [comment]
Same problem here
I guess everyone with 2023.8.4 is having the same issue. Does anyone know if someone is working on the issue?

**Comment by ryanhindinger** [comment]
Also having this issue.  I can see the colors and formatting when editing or creating the card, but as soon as I leave the edit mode, all of that is lost.

**Comment by adechant** [comment]
My suspicion is that this is not a HA frontend bug, but a bug in the fullcalendar code (see https://github.com/fullcalendar/fullcalendar/issues/7447). I've managed to replicate the infinite event loop described here within home assistant, and I think it is leading to the formatting issue. Workaround is to add "eventOrderStrict: true" to the defaultFullCalendarConfig: CalendarOptions in ha-full-calendar.ts at least until the next update of fullCalendar after 6.1.8.

**Comment by ragesoft** [comment]
Issue still exists in latest HA version...

Home Assistant 2023.9.2
Supervisor 2023.09.2
Operating System 10.5
Frontend 20230911.0 - latest

**Comment by karwosts** [comment]
Fixed by #18381

**Comment by schwartzpub** [comment]
This is still happening after latest release:
Home Assistant 2023.10.5
Supervisor 2023.10.0
Operating System 11.0
Frontend 20231005.0 - latest

**Comment by karwosts** [comment]
It's fixed in 2023.11, you'll need next week's release (or the beta).
