### ISSUE TITLE
"Delay Translation Error" in UI Editor

### ISSUE THREAD

**Issue by bachya** [home-assistant/frontend#17173]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I insert a `delay` action in the automation UI editor and save it, the label contains an exception:

<img width="1022" alt="CleanShot 2023-07-05 at 11 55 49@2x" src="https://github.com/home-assistant/frontend/assets/47216/bf589ac8-683e-47e4-ab9e-573cbc5a5bfe">

### Describe the behavior you expected

The label should show what it's intended to show.

### Steps to reproduce the issue

1. Create a new automation via the UI.
2. Add a `Wait for time to pass (delay)` action.
3. Enter any duration for the action and save it.

### What version of Home Assistant Core has the issue?

core-2023.7.0b6

### What was the last working version of Home Assistant Core?

?

### In which browser are you experiencing the issue with?

Firefox 114.0.2

### Which operating system are you using to run this browser?

macOS Ventura 13.4.1

### Problem-relevant frontend configuration

```yaml
delay:
  hours: 0
  minutes: 1
  seconds: 0
  milliseconds: 0
```

**Comment by silamon** [comment]
It should be fixed already by #17166 which was merged for the July release.

**Comment by bachya** [comment]
I'm just updated to the 2023.7.0 GA release and the issue still exists.

**Comment by tbclark3** [comment]
I'm also on 2023.7.0 and seeing the same error.

**Comment by limitless00net** [comment]
same here

**Comment by karwosts** [comment]
Looks like the change did not make it in time for 2023.7.0, it is tagged for 2023.7.1.

**Comment by bramkragten** [comment]
Was fixed in https://github.com/home-assistant/frontend/pull/17166
