### ISSUE TITLE
Energy Dashboard uses only the left half

### ISSUE THREAD

**Issue by totow93** [home-assistant/frontend#18514]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The Energy Dashboard uses only the left 50% of the screen.
![image](https://github.com/home-assistant/frontend/assets/100964266/cf351d0c-b812-40b7-a7d0-9ece6ec82c2f)

### Describe the behavior you expected

That it uses all the space

### Steps to reproduce the issue

1. Open the Energy Daschboard

### What version of Home Assistant Core has the issue?

2023.11.0

### What was the last working version of Home Assistant Core?

2023.10.X

### In which browser are you experiencing the issue with?

Brave Version 1.60.110 Chromium: 119.0.6045.105 (Offizieller Build) (64-Bit) / Microsoft Edge Version 118.0.2088.76 (Offizielles Build) (64-Bit)

### Which operating system are you using to run this browser?

Windows 10 22H2

### Problem-relevant frontend configuration

```yaml
Frontend: 20231030.1
```

### Additional information

Supervisor: 2023.10.1
Operating System: 11.1 Virtual Machine ova

**Comment by Eyco1981** [comment]
Are you using card mod from HACS?
Updating that to 3.2.4 and refreshing the browser cache should fix it.

**Comment by totow93** [comment]
Thanks that was the problem.

**Comment by ahlstromanton** [comment]
Upgrading card-mod did not solve the problem for me. I've cleared cache, restarted HA.

**Comment by silamon** [comment]
> Upgrading card-mod did not solve the problem for me. I've cleared cache, restarted HA.

You can try the new safe mode: https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode
If the problem persists in safe restart mode, then it's most likely something that's for this repo.
