### ISSUE TITLE
Webview crashing/reloading on Home assistant App

### ISSUE THREAD

**Issue by bambucha3** [home-assistant/frontend#21900]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have three NSPanel PROs, running Android 8.1 and running Home assistant app 2024.7.3-minimal.
I am using Sections view on all of them.
Since the update, the panels have been restarting/reloading the dashboard in an infinite loop.
Reverting to 2024.8 fixed the issue.

### Describe the behavior you expected

Not crashing.

### Steps to reproduce the issue

1. Opened sections dashboard on device

### What version of Home Assistant Core has the issue?

core-2024.9

### What was the last working version of Home Assistant Core?

core-2024.8.3

### In which browser are you experiencing the issue with?

Home assistant app 2024.7.3-minimal

### Which operating system are you using to run this browser?

Android 8.1

**Comment by zamansoum** [comment]
seems related to #21879

**Comment by bambucha3** [comment]
> seems related to #21879

Yes, looks thee same.
Bad thing is, i cant upgrade webview on my NSPanels without rooting them (or so i understand)..

**Comment by rouxdoo** [comment]
I have the same issue on an older iPad Pro that I'm using as a kiosk. If I go to a dashboard with sections view it will crash loop then fail to load on Safari and HA app both. I cleared all cache and website data with no change in behavior. This does not happen on iOS or macOS, only on iPadOS (16.7.10).

**Comment by Tykwondo1** [comment]
looks the same

**Comment by miketague** [comment]
Exactly the same issues on all my Fire tablets

**Comment by gitzappo** [comment]
I'm facing the same issue using HA Companion **App** 2024.8.1. (2024.791).
Dashboards using the sections feature leads to continuously  reloading the page if HA core 2024.9.0 is installed.

**Comment by technoman63** [comment]
I have the same issues on my Sonoff Nspanel in Fully Kiosk Browser and the HA app, all time the apps crash.

**Comment by lviciedo** [comment]
xactly the same issues on all my Fire tablets running Fully Kios Browser

**Comment by Tykwondo1** [comment]
I have two fire tablets and they are on my IoT network where I block the internet so my tablets were not up to date. So I connected the tablets to my network with the internet and checked the updates, there were 24, I did the manual updates by pushing the update button several times until zero. I put my table back on my network without internet, relaunch Fully Kios Browser, AND VOILA

**Comment by catdogmaus** [comment]
Same with my Yoga tab. Issue is with Sections, when I am fast enough to open any other view before sections loads, everything is fine. Switching to sections dashboard again crashes it immediately. Kiosk mode _per se_ in my opinion has nothing to do with it.

**Comment by silamon** [comment]
There's probably something going on that older browsers cannot parse that was introduced as new feature in the sections view. 
If there's anybody who can reproduce this in a browser (not the companion app), we do have daily demo deployments at https://github.com/home-assistant/frontend/actions/workflows/demo_deployment.yaml?query=event%3Aschedule. You can click one open, then see the url of the frontend at that day. Finding the oldest where everything is working, would help towards resolution. 

At this point, if you're experiencing the same issue but cannot add more information to what is already provided, just give a thumbs up to the initial post.

**Comment by alexpfau** [comment]
Same issue here with fully kiosk running on a Fire tablet

**Comment by rchiileea** [comment]
> > > seems related to #21879
> > 
> > 
> > Yes, looks the same. Bad thing is, i cant upgrade webview on my NSPanels without rooting them (or so i understand)..
> 
> You can, with this guide: https://github.com/seaky/nspanel_pro_tools_apk?tab=readme-ov-file#install-custom-webview You override the existing webview.

webview update does not fix this

**Comment by EvanMulawski** [comment]
@silamon I can't seem to find a demo deployment that causes the crash. Currently testing some different scenarios locally.

---

adb logcat output, crashpads omitted:

```log
09-07 14:02:23.035 10162 10162 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 10176 <<<<<<
09-07 14:02:23.135 10162 10162 I /system/bin/app_process64: The ClassLoaderContext is a special shared library.
09-07 14:02:23.136 10162 10162 I /system/bin/app_process64: The ClassLoaderContext is a special shared library.
09-07 14:02:23.151 10162 10164 I /system/bin/app_process64: Bumping SignalCatcher priority from 7 to 10
09-07 14:02:23.186 10162 10162 D AmazonDisplayManagerGlobal: Successfully loaded all classes
09-07 14:02:23.186 10162 10162 D AmazonDisplayManagerGlobal: Successfully loaded all fields
09-07 14:02:23.199 10162 10162 D AndroidRuntime: Calling main entry org.chromium.components.crash.browser.CrashpadMain
09-07 14:02:23.204 10162 10162 W linker  : Warning: "/system/app/AmazonWebView/AmazonWebView.apk!/lib/arm64-v8a/libwebviewextchromium.so" unused DT entry: unknown processor-specific (type 0x70000001 arg 0x0) (ignoring)
09-07 14:02:23.537 10162 10162 W chromium: [0907/140223.536754:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
09-07 14:02:23.533 10162 10162 W main    : type=1400 audit(0.0:1564): avc: denied { getsched } for scontext=u:r:untrusted_app:s0:c176,c256,c512,c768 tcontext=u:r:isolated_app:s0:c8,c256,c512,c768 tclass=process permissive=0
09-07 14:02:23.537 10162 10162 W chromium: [0907/140223.537914:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
09-07 14:02:23.538 10162 10162 W chromium: [0907/140223.538211:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
09-07 14:02:23.538 10162 10162 W chromium: [0907/140223.538507:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
09-07 14:02:23.538 10162 10162 W chromium: [0907/140223.538726:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
09-07 14:02:23.533 10162 10162 W main    : type=1400 audit(0.0:1565): avc: denied { getsched } for scontext=u:r:untrusted_app:s0:c176,c256,c512,c768 tcontext=u:r:isolated_app:s0:c8,c256,c512,c768 tclass=process permissive=0
09-07 14:02:23.539 10162 10162 W chromium: [0907/140223.539903:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
09-07 14:02:23.540 10162 10162 W chromium: [0907/140223.540573:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
09-07 14:02:23.540 10162 10162 W chromium: [0907/140223.540886:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
09-07 14:02:23.541 10162 10162 W chromium: [0907/140223.541203:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
09-07 14:02:23.541 10162 10162 W chromium: [0907/140223.541548:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
09-07 14:02:23.542 10162 10162 W chromium: [0907/140223.541991:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
09-07 14:02:23.542 10162 10162 W chromium: [0907/140223.542396:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
09-07 14:02:23.542 10162 10162 W chromium: [0907/140223.542758:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
09-07 14:02:23.543 10162 10162 W chromium: [0907/140223.543146:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
09-07 14:02:23.543 10162 10162 W chromium: [0907/140223.543438:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
09-07 14:02:23.543 10162 10162 W chromium: [0907/140223.543874:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
09-07 14:02:23.544 10162 10162 W chromium: [0907/140223.544201:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
09-07 14:02:23.544 10162 10162 W chromium: [0907/140223.544580:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
09-07 14:02:23.545 10162 10162 W chromium: [0907/140223.544990:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
09-07 14:02:23.545 10162 10162 W chromium: [0907/140223.545283:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
09-07 14:02:23.545 10162 10162 W chromium: [0907/140223.545593:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
09-07 14:02:23.546 10162 10162 W chromium: [0907/140223.546034:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
09-07 14:02:23.546 10162 10162 W chromium: [0907/140223.546484:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
09-07 14:02:23.547 10162 10162 W chromium: [0907/140223.546992:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
09-07 14:02:23.547 10162 10162 W chromium: [0907/140223.547423:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
09-07 14:02:23.547 10162 10162 W chromium: [0907/140223.547807:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
09-07 14:02:23.557 10162 10162 E chromium: [0907/140223.557640:ERROR:ptrace_client.cc(363)] Broker Open: access denied
09-07 14:02:23.606 10162 10162 F crashpad: -----BEGIN CRASHPAD MINIDUMP-----
09-07 14:02:23.675 10162 10162 F crashpad: -----END CRASHPAD MINIDUMP-----
09-07 14:02:23.676  1752  1752 W BSTN_MapClient: empty account, retry in 1000
09-07 14:02:23.707 10162 10162 E chromium: [0907/140223.707064:ERROR:socket.cc(182)] incorrect payload size 0
09-07 14:02:23.707 10068 10083 E libc    : failed to connect to tombstoned: Operation not permitted
09-07 14:02:23.707 10162 10162 D AndroidRuntime: Shutting down VM
09-07 14:02:23.951   653  9824 I ActivityManager: Process com.amazon.webview.chromium:sandboxed_process8 (pid 10068) has died: fore TOP
09-07 14:02:23.951  1806  1806 I Zygote  : Process 10068 exited due to signal 5 (Trap)
09-07 14:02:23.952  4435  4755 W cr_ChildProcessConn: onServiceDisconnected (crash or killed by oom): pid=10068 bindings:W  S
09-07 14:02:23.954   653  9824 W ActivityManager: Scheduling restart of crashed service de.ozerov.fully/org.chromium.content.app.SandboxedProcessService8 in 2000ms
09-07 14:02:23.957   653   675 W libprocessgroup: Failed to open process cgroup uid 99008 pid 10068: No such file or directory
09-07 14:02:23.957   653   675 E libprocessgroup: Error encountered killing process cgroup uid 99008 pid 10068: No such file or directory
09-07 14:02:23.968  4435  4435 E chromium: [ERROR:aw_browser_terminator.cc(156)] Renderer process (10068) crash detected (code 5).
09-07 14:02:23.971  4435  4435 W MyWebViewClient: onRenderProcessGone
09-07 14:02:23.971  4435  4435 E MyWebViewClient: The WebView rendering process crashed! Restarting app...
09-07 14:02:23.978   653  1712 W Eve     : MEMORY_LEVEL: [10068,0]
09-07 14:02:23.978   653  1712 W Eve     :   top=de.ozerov.fully/.FullyActivity launching=false
09-07 14:02:23.978   653  1712 W Eve     :   prev=de.ozerov.fully/.ScreensaverActivity screen_on=true thermal=0
09-07 14:02:23.978   653  1712 W Eve     :   adb=true downloading=false gamemode=true
09-07 14:02:23.978   653  1712 W Eve     :   memory=0 trim=5 available=2271932KB free=530520KB
```

**Comment by EvanMulawski** [comment]
@silamon I think I found it:

- [**4621**](https://github.com/home-assistant/frontend/actions/runs/10587835522) does not crash when navigating to the demo Dashboard from another page (e.g. Map).
- [**4637**](https://github.com/home-assistant/frontend/actions/runs/10606385281) DOES crash when navigating to the demo Dashboard from another page (e.g. Map).

**Comment by EvanMulawski** [comment]
@silamon Narrowed it down to [4628](https://github.com/home-assistant/frontend/actions/runs/10592522444), which is a Sections change (https://github.com/home-assistant/frontend/commit/5a229e3c8818d1298660d67b9982474e391d989a). 4627 does not crash.

**Comment by gerben-f1** [comment]
Here it crashes also on a fire tab hd 10

**Comment by EvanMulawski** [comment]
> Here it crashes also on a fire tab hd 10 Solutiin for me was updating the tablet with newest software version
> 
> 7.3.3.0

Confirmed. Just updated to 7.3.3.0 (which must be _very_ new - not even on Amazon's Fire OS updates page) and it is no longer crashing on HA 2024.9.1. Update 7.3.3.0 packages WebView v118 versus v114 in 7.3.2.9.

**Comment by ViperRNMC** [comment]
> > Here it crashes also on a fire tab hd 10 Solutiin for me was updating the tablet with newest software version
> > 7.3.3.0
> 
> Confirmed. Just updated to 7.3.3.0 (which must be _very_ new - not even on Amazon's Fire OS updates page) and it is no longer crashing on HA 2024.9.1. Update 7.3.3.0 packages WebView v118 versus v114 in 7.3.2.9.

thanks for the trigger webview, update webview on mij nspanel pro and now 2024.9.1 works great

**Comment by bambucha3** [comment]
@ViperRNMC What firmware did you update to exactly? Did you just install an apk using adb?
I had some trouble updating my nspanel pros.. would appreciate help :)

**Comment by ViperRNMC** [comment]
> @ViperRNMC What version did you update to exactly, do you have a link? Did you just install an apk using adb? I had some trouble updating my nspanel pros.. would appreciate help :)

Newest with adb install

https://apkpure.com/android-system-webview/com.google.android.webview/downloading

**Comment by bambucha3** [comment]
> > @ViperRNMC What version did you update to exactly, do you have a link? Did you just install an apk using adb? I had some trouble updating my nspanel pros.. would appreciate help :)
> 
> Newest with adb install
> 
> https://apkpure.com/android-system-webview/com.google.android.webview/downloading

Thank you, it installed fine with ADB.
How do you then select which webview homeassistant app uses? In Dev options I only see the old one.

**Comment by ViperRNMC** [comment]
https://github.com/neoblackxt/AnyWebView/releases/

**Comment by piitaya** [comment]
I was able to find the issue. The fix should be part of the next patch. Thank you all for isolating the problem, it helped a lot for debugging.

**Comment by piitaya** [comment]
`2024.9.2` is out. It should be fixed. Don't hesitate to comment if it's resolved or not 🙂

**Comment by bambucha3** [comment]
@piitaya Good news! Can confirm working on all my NSPanel Pros! Thank you 😁

**Comment by rouxdoo** [comment]
Fixed on my old iPad Pro. Thanks!

**Comment by totolook** [comment]
Fixed on my iPhone X (iOS 16)

**Comment by DeckardCain2014** [comment]
I'm using a Fire Tablet and it's not fixed - using Amazon Webview 128.6613.187.18

**Comment by piitaya** [comment]
@DeckardCain2014 Try clearing your cache or uninstalling/reinstalling Mushroom.

**Comment by foxcris** [comment]
@DeckardCain2014 are you using the Fully Kios Browser? With it had to use the option to reset webview on onw of my devices.

**Comment by DeckardCain2014** [comment]
> @DeckardCain2014 are you using the Fully Kios Browser? With it had to use the option to reset webview on onw of my devices.

I am, however I need to use an old version as my Fire Tablet is quite old

**Comment by Reachushere** [comment]
I have 7 fire tablets - same issue here.  Closes randomly.  All of my tablets are set to the same custom dashboard (a picture elements card as the entire background), and a crash will happen on two or three of the tablets,  but not others.  All of my talbets are 10" and up to date with the latest OS.  So there is effectively no difference between them but the crash only happens with some of them, and it is never consistent which ones, but it is often more than one at a time.

**Comment by DeckardCain2014** [comment]
I have a brand new Fire HD8 Tablet now, still the same issue

**Comment by DeckardCain2014** [comment]
@piitaya Can you please reopen? I think it is still not fixed on every device, especially not the Amazon FireHD tablets with their Amazon Webview implementation.
Can I somehow support you with logs, reports, or anything?

**Comment by piitaya** [comment]
If you could have logs from the browser? It can help as I don't have Amazon FireHD tablet to test. I'm not sure how to get this browser logs from a fire tablet.
Do you know which browser and version it is using?

**Comment by DeckardCain2014** [comment]
I'm using the Fully Kiosk Browser version 1.56.2.
It relies on Amazon WebView 126.0.6478.186
I'm afraid I don't know how to log something in the app.

**Comment by piitaya** [comment]
Can you try with the [4.2.1](https://github.com/piitaya/lovelace-mushroom/releases/tag/v4.2.1) release?

**Comment by DeckardCain2014** [comment]
I will, thank you!

**Comment by piitaya** [comment]
@DeckardCain2014 I deleted my comment as it was not relevant, I confused this bug with another one...
Do you know if it worked with an older version of HA? Also, can you try in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode)?

**Comment by DeckardCain2014** [comment]
Hi @piitaya ,
I tested for 2 hours on safemode, normally it breaks in this time. In safemode, no problems with a crashing webview.

**Comment by DeckardCain2014** [comment]
Anything else I can try?

**Comment by piitaya** [comment]
Then I think it's an issue with a custom cards. You can take a look on this side by looking at the different issues on the repository of each card and by trying to uninstall them to find the culprit.
There is nothing we can do in the frontend of Home Assistant if it's a custom card issue.
