### ISSUE TITLE
Hold action not working for image element in picture-elements card in android app

### ISSUE THREAD

**Issue by queimadus** [home-assistant/frontend#23305]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When using a image element inside a picture-elements card, the hold_action (long press) is not working. After the long press, we see some visual response in the bottom left of the screen but the action does not trigger.

I've tested that this doesn't happen using the browser version of lovelace so It seems it is only manifesting in with the android app. I opened a [issue there](https://github.com/home-assistant/android/issues/4908) but was forwarded here.

I include a reproducible snippet (might have to change the entity to something that exists) 

```
type: picture-elements
image: https://demo.home-assistant.io/stub_config/floorplan.png
elements:
  - type: image
    image: >-
      https://images.rawpixel.com/image_png_800/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDI0LTAxL2Rlc2lnbndpdGhtZTA5X2FfbGlnaHRfYnVsYl9pbl90aGVfc3R5bGVfb2ZfaHlwZXItcmVhbGlzdGljX2lsbF9iMTE2ZmI3Zi1kYzc4LTQ1MDEtYWQwNC05NDY4YjVlNzU2ZjAucG5n.png
    style:
      top: 50%
      left: 50%
      width: 15%
    tap_action:
      action: toggle
    entity: light.bathroom_office

```

take notice of the flashing on the bottom left corner

https://github.com/user-attachments/assets/43d7a3fd-e617-4bbe-847f-c73162cb7ce1

### Describe the behavior you expected

When long pressing the icon, the defined hold_action triggers (as it happens in non-android envs)

https://github.com/user-attachments/assets/5e8e6189-a9e7-4f68-93a4-c3a33c730537

### Steps to reproduce the issue

1. Create a widget as defined in the above snippet
2. Change the entity to something that exists in your system
3. Long press the bulb image

### What version of Home Assistant Core has the issue?

core-2024.12.3

### What was the last working version of Home Assistant Core?

core-2024.11.X

### In which browser are you experiencing the issue with?

Android 14 (One UI 6.1)

### Which operating system are you using to run this browser?

Android 14 (One UI 6.1)

**Comment by n1njaduck** [comment]
Same issue here

**Comment by ESP4Ever** [comment]
Hi!
Same issue for some of my Android devices.
I configured a dimmer control to use "tap" as "toggle" and "hold" as "more info" actions but the dimmer control window popups only on PC and old Samsung Tab 3

**Comment by majkers** [comment]
Same for me

**Comment by Je-sse** [comment]
Same for me. Only happens when using an image, no problems with state icon, state label, etc. Problem exists on all three Android devices we use.
Also a video from me:

https://github.com/user-attachments/assets/3cf68161-bb5f-4404-b216-6043270dd58c

**Comment by heisenberg2980** [comment]
Same issue here, and I thought it was weird because holding actually worked for some of the elements of my floorplan while it didn´t work for most of them, but I just realised it works on all the icons and not on the images, which makes sense and is aligned to the title of this issue.

**Comment by Je-sse** [comment]
I also noticed that if you release just before the circle appears in the lower left, the hold action is performed. It's a very short time window

**Comment by heisenberg2980** [comment]
@Je-sse that´s a great discovery and a bit of a workaround until this issue is solved, thanks for sharing!

**Comment by Je-sse** [comment]
I have just installed version 2025.1 and can confirm that the problem still exists.

**Comment by Buckeyes1995** [comment]
I can add that I cannot get HOLD ACTION or DOUBLE_TAP_ACTION to work on a picture-elements card.  Either on PC (Chrome) or Android M11 Tab through Fully Kiosk Browser.  Double tap immediately brings up single tap result, and hold action says "No entity provided for more info dialog".

**Comment by heisenberg2980** [comment]
@Buckeyes1995 both HOLD and DOUBLE_TAP work for me on PC (Chrome), and DOUBLE_TAP also works on Android, so I guess you might be doing something wrong. The only issue is with HOLD action on Android.

**Comment by Buckeyes1995** [comment]
> @Buckeyes1995 both HOLD and DOUBLE_TAP work for me on PC (Chrome), and DOUBLE_TAP also works on Android, so I guess you might be doing something wrong. The only issue is with HOLD action on Android.

I don't mean to highjack this Android specific thread, but not sure what I would be doing wrong.. code below.  Script runs fine on its own.

`         
- type: icon
            icon: mdi:alarm-light
            style:
              left: 75%
              top: 15%
              opacity: 75%
              transform: scale(3.0,3.0)
              color: red
            hold_action:
              action: perform_action
              confirmation: false
              perform_action: script.turn_on_overhead_lights_and_raise_blinds
`

**Comment by heisenberg2980** [comment]
That´s an icon instead of a picture-element, but anyway try this and then hold the icon from your PC. If it works and it shows you the details of the entity you will know that hold action works:

```
      - type: icon
        icon: mdi:alarm-light
        style:
          left: 75%
          top: 15%
          opacity: 75%
          transform: scale(3.0,3.0)
          color: red
        hold_action:
          action: more-info
```

**Comment by Buckeyes1995** [comment]
> That´s an icon instead of a picture-element, but anyway try this and then hold the icon from your PC. If it works and it shows you the details of the entity you will know that the hold action works:
> 
> ```
>       - type: icon
>         icon: mdi:alarm-light
>         style:
>           left: 75%
>           top: 15%
>           opacity: 75%
>           transform: scale(3.0,3.0)
>           color: red
>         hold_action:
>           action: more-info
> ```

It's an icon in a picture-elements card;  adding more-info does not do anything when I tap and hold.  Very odd.

**Comment by jdandrea** [comment]
Possibly related (I can file a new issue if that would be better): This also appears to be the case for Tile Cards on iOS, via the web or from within the app. 

I do find that I can make the hold behavior interaction take effect if I _very carefully_ time my tap-and-hold gesture to let go the instant before the superimposed blue circle appears. As such it's very hit-or-miss, and it makes the hold interaction unusable.

Contrast this with a desktop web browser: At any point in time after the blue circle appears, I can let go of the mouse button and it works, every time.

**Comment by Buckeyes1995** [comment]
I'm using Browser Mod to pop up other entities on my floorplan. I thought I figured it out by use a browser mod sequence event.. it worked for the first element in the list, but not subsequent.  Whenever I click on subsequent I get a "No entity provided for more info dialog".  See code below.  These are icon elements overlaying my floorpan image.  A tap action creates mushroom pop ups and works fine.. a hold action works fine on 'front office' but the next one 'living room' does not work... very odd.

`          #####################################################################################################
          # FRONT OFFICE
          #####################################################################################################
          - type: icon
            icon: mdi:desk
            style:
              left: 78.2%
              top: 75%
              opacity: 75%
              transform: scale(1.75,1.75)
              color: orange
            tap_action:
              action: fire-dom-event
              browser_mod:
                service: browser_mod.popup
                data:
                  content:
                    type: vertical-stack
                    cards:
                      - type: custom:mushroom-title-card
                        title: Front Office
                        alignment: justify
                      - type: custom:mushroom-chips-card
                        chips:
                          - type: menu
                          - type: entity
                            entity: sensor.main_floor_temperature
                            icon_color: orange
                          - type: entity
                            entity: sensor.main_floor_humidity
                            icon_color: indigo
                          - type: template
                            content: |-
                              {% set lights = ['light.front_office_overhead_lights_dimmer',
                              'light.front_office_desk_lamp', 'light.front_office_fan_light'] %}
                              {% set total = lights|select('is_state', 'on')|list|count %}
                              ({{total}}) Lights ON
                            icon: mdi:lightbulb-group
                            icon_color: |-
                              {% set lights = ['light.front_office_overhead_lights_dimmer',
                              'light.front_office_desk_lamp', 'light.front_office_fan_light'] %}
                              {% set total = lights|select('is_state', 'on')|list|count %}
                              {% if total > 0 %}
                                orange
                              {% else %}
                                grey
                              {% endif %}
                          - type: template
                            content: |-
                              {% if is_state('fan.front_office_fan', 'on') %}
                                 Fan is ON
                              {% else %}
                                 Fan is OFF
                              {% endif %}
                            icon: mdi:fan
                            icon_color: |-
                              {% if is_state('fan.front_office_fan', 'on') %}
                                green
                              {% else %}
                                grey
                              {% endif %}
                      - type: horizontal-stack
                        cards:
                          - type: custom:mushroom-light-card
                            entity: light.front_office_overhead_lights_dimmer
                            show_brightness_control: true
                          - type: custom:mushroom-light-card
                            entity: light.front_office_desk_lamp
                            show_brightness_control: true
                      - type: horizontal-stack
                        cards:
                          - type: custom:mushroom-fan-card
                            entity: fan.front_office_fan
                            icon_animation: true
                            show_percentage_control: true
                          - type: custom:mushroom-light-card
                            entity: light.front_office_fan_light
            hold_action:
              action: fire-dom-event
              browser_mod:
                service: browser_mod.sequence
                data:
                  sequence:
                    - service: light.toggle
                      data:
                        entity_id: light.front_office_lights_group
            # double_tap_aciton:
            #   action: toggle

          #####################################################################################################
          # LIVING ROOM
          #####################################################################################################
          - type: icon
            icon: mdi:sofa-single
            #            entity: light.living_room_lights_group
            style:
              left: 73%
              top: 50%
              opacity: 75%
              transform: scale(1.75,1.75)
              color: orange
            tap_action:
              action: fire-dom-event
              browser_mod:
                service: browser_mod.popup
                data:
                  content:
                    type: vertical-stack
                    cards:
                      - type: custom:mushroom-title-card
                        title: Living Room
                        alignment: justify
                      - type: custom:mushroom-chips-card
                        chips:
                          - type: menu
                          - type: entity
                            entity: sensor.main_floor_temperature
                            icon_color: orange
                          - type: entity
                            entity: sensor.main_floor_humidity
                            icon_color: indigo
                          - type: template
                            content: |-
                              {% set lights = ['light.living_room_overhead_lights_dimmer',
                              'light.living_room_floor_lamp', 'light.living_room_fan_light'] %}
                              {% set total = lights|select('is_state', 'on')|list|count %}
                              ({{total}}) Lights ON
                            icon: mdi:lightbulb-group
                            icon_color: |-
                              {% set lights = ['light.living_room_overhead_lights_dimmer',
                              'light.living_room_floor_lamp', 'light.living_room_fan_light'] %}
                              {% set total = lights|select('is_state', 'on')|list|count %}
                              {% if total > 0 %}
                                orange
                              {% else %}
                                grey
                              {% endif %}
                          - type: template
                            content: |-
                              {% if is_state('fan.living_room_fan', 'on') %}
                                 Fan is ON
                              {% else %}
                                 Fan is OFF
                              {% endif %}
                            icon: mdi:fan
                            icon_color: |-
                              {% if is_state('fan.living_room_fan', 'on') %}
                                green
                              {% else %}
                                grey
                              {% endif %}
                      - type: horizontal-stack
                        cards:
                          - type: custom:mushroom-light-card
                            entity: light.living_room_overhead_lights_dimmer
                            show_brightness_control: true
                          - type: custom:mushroom-light-card
                            entity: light.living_room_floor_lamp
                            show_brightness_control: false
                      - type: horizontal-stack
                        cards:
                          - type: custom:mushroom-fan-card
                            entity: fan.living_room_fan
                            icon_animation: true
                            show_percentage_control: true
                          - type: custom:mushroom-light-card
                            entity: light.living_room_fan_light
            hold_aciton:
              action: fire-dom-event
              browser_mod:
                service: browser_mod.sequence
                data:
                  sequence:
                    - service: light.toggle
                      data:
                        entity_id: light.living_room_lights_group
            # double_tap_aciton:
            #   action: toggle`

**Comment by jdandrea** [comment]
> Buckeyes1995

Not sure if it's coded this way on purpose, but should `aciton` read `action` everywhere in your snippet?

**Comment by Buckeyes1995** [comment]
> @Buckeyes1995: Not sure if it's coded this way on purpose, but should `aciton` read `action` everywhere it occurs in your snippet instead? (Been there, tpyo'ed that!)

Wow.. good catch..  I'm an idiot.  Stared at it for a long time and didn't see that... turns out that works :). thanks!  Still wish I knew why the native hold_action doesn't work.. but at least I have a workaround using browser mod.

**Comment by ippo112** [comment]
same issue for me on HA 2025.1.2 (Frontend 20250109.0).

**Comment by n1njaduck** [comment]
Issue continues in:

Core: 2025.2.1
Supervisor: 2025.02.0
Operating System: 14.2
Frontend: 20250205.0

**Comment by n1njaduck** [comment]
Issue continues in:

Core 2025.2.2
Supervisor 2025.02.0
Operating System 14.2
Frontend 20250210.0

**Comment by Sunxperous** [comment]
I briefly skimmed through recent changes and #22852 seems relevant given that it fixes something specific for the HA Android app and not for browsers, and the timeline fits as well (commit in Nov 2024, this surfaced in 2024.12). As stated in https://github.com/home-assistant/frontend/issues/23305#issuecomment-2566970489 and https://github.com/home-assistant/frontend/issues/23305#issuecomment-2577859333, there is a sliver of time where the `hold_action` successfully triggers, so the ordering of `touchstart`, `touchmove`, `touchcancel`,  and `touchend` events from **WebView** may differ from native browsers causing this issue.

@Ongion @mattyway any thoughts on this?

**Comment by zeronounours** [comment]
Hello,
I have the same issue with my floorplan. I did some remote webview debugging to find out the issue and indeed @Sunxperous is pointing to the right PR.

When holding an image in a picture-element, the webview quickly send a `touchcancel` event, leading to the `element.actionHandler.end` handler to stop early. However, `this.cancelled` is `false`. When `touchcancel` is triggered, `this.held` is correctly set to `true` at that time, because it was held long enough.

Note: this happens even if the touch is not released.

**Comment by mikaeltarquin** [comment]
Just commenting that this is also a problem for me. I want to use hold_actions, but they only trigger in a web browser and not the Android app. Very disappointing, gotta switch to double taps for now I guess.

**Comment by Je-sse** [comment]
I found a workaround for this because I had one image where I really needed the hold_action. I set both actions for the **image** to none. Then, I added a state-label with the same entity. The **state-label** has the right actions configured, but the text is set to be transparent. This way, the text is not visible, but the correct actions are still executed. I believe the same approach could work with an icon, but this solution works for me.

This is my code:
```
  - type: image
    image: /path/image.png
    entity: input_boolean.XXX
    hold_action:
      action: none
    tap_action:
      action: none
    style:
      top: X%
      left: X%
  - type: state-label
    entity: input_boolean.XXX     # same as above
    style:
      top: X%     # same as above
      left: X%     # same as above
    tap_action:
      action: url
      url_path: https://somesite.com/
    hold_action:
      action: toggle
```

**Comment by mrgrlscz** [comment]
Hi, same problem here, hold_action do not trigger on android app, everything is ok on desktop.
`Je-sse`'s workaround is ok for small image elements
In my case the image hosting the hold_action is the whole card... so.... waiting for a fix.

**Comment by jeremicmilan** [comment]
I hit the same issue. But for me hold and double tap do not work on any device. Found the following [commit](https://github.com/home-assistant/frontend/commit/5237cc72b7de6c98ec6958ce5d501432799ec9f0).
@piitaya, @bramkragten, will your commit fix this issue?

**Comment by jeremicmilan** [comment]
Just upgraded Home Assistant core from 2025.4.1 to 2025.4.2 and the issue is fixed. :) 
Looking at the [release notes](https://www.home-assistant.io/blog/2025/04/02/release-20254/), I find this:
- Update frontend to 20250411.0 ([@bramkragten](https://github.com/bramkragten) - [142736](https://github.com/home-assistant/core/pull/142736))

Which picks up the commit I mentioned in the previous comment:
![Image](https://github.com/user-attachments/assets/3d745af8-a7f3-4cdc-a61d-87830f51e67d)

Can anybody from this thread confirm the issue is fixed?

**Comment by kmorrow429** [comment]
@jeremicmilan  I'm running 2025.4.2 and still having this issue. However, now when I hold the image it acts like I'm trying to drag and drop it, which I don't believe it did before

**Comment by Satoxian** [comment]
Im updating now ha now will post my findings.

**Comment by Mars-Pathfinder** [comment]
I updated today to 2025.4.2 and continue to observe the same bugged behavior.

**Comment by Satoxian** [comment]
Same thing  however I was able to just program more info to pop up on
double tap

**Comment by n1njaduck** [comment]
Issue continues in:

Core: 2025.5.2
Supervisor: 2025.05.1
Operating System: 15.2
Frontend: 20250516.0

Android App:
Version: 2025.4.3-full
Device: SAMSUNG SM-s936B

**Comment by woempiej** [comment]
Hi all,

@queimadus thanks for reporting!

This issue still occurs in:
Installatiemethode Home Assistant OS
Core 2025.6.3
Supervisor 2025.06.2
Operating System 15.2
Frontend 20250531.4

Use it for Alexa devices to play TUNEIN
Press, play on living room group
Hold, play on everywhere group <-- Doesn't work in Android companion app

**Comment by Reachushere** [comment]
This issue occurs for me in

Installation method Home Assistant OS
Core 2025.7.1
Supervisor 2025.06.2
Operating System 15.2
Frontend 20250702.1

It means none of my rooms will open when I press them on my dashboard.  This is a severely crippling issue, does anyone have any solutions?  It works on my PC when I click and hold the mouse, but I have 12 Fire Tablets, mostly Fire 10's, but hold action won't work on any of them.

**Comment by n1njaduck** [comment]
Issue continues in:

Core 2025.7.2
Supervisor 2025.07.1
Operating System 16.0
Frontend 20250702.2

Android App:
Version: 2025.7.1-full
Device: SAMSUNG SM-s936B

**Comment by yldrmzffr** [comment]
Still experiencing this issue.

**System Information:**
- Core: 2025.8.1
- Supervisor: 2025.08.1  
- Operating System: 16.1
- Frontend: 20250811.0

**Comment by Je-sse** [comment]
With the [new Android release](https://github.com/home-assistant/android/releases/tag/2025.8.7) (2025.8.7), it is no longer possible to use the workaround of releasing just before the circle appears in the lower-left corner to trigger the hold action.
I hope [this fix](https://github.com/home-assistant/frontend/pull/26647) will solve the issue and be rolled out soon.

**Comment by Reachushere** [comment]
Sorry, I understand the problem. I experienced it myself.  I don't understand what the fix is.  What do I need to do?

**Comment by woempiej** [comment]
> With the [new Android release](https://github.com/home-assistant/android/releases/tag/2025.8.7) (2025.8.7), it is no longer possible to use the workaround of releasing just before the circle appears in the lower-left corner to trigger the hold action. I hope [this fix](https://github.com/home-assistant/frontend/pull/26647) will solve the issue and be rolled out soon.

Maybe wait for a new Android release? I am on 2025.8.7-full
