### ISSUE TITLE
2025.2.0b0 height does not scale for standard energy graphs

### ISSUE THREAD

**Issue by VinceRMP** [home-assistant/frontend#23941]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

After the changes to the graphs in beta they default energygraphs are very large in height. 

Old height:

![Image](https://github.com/user-attachments/assets/562223d8-2d7d-459e-842f-b0a827544c50)

New height:

![Image](https://github.com/user-attachments/assets/47ca69fa-604d-411a-b264-a0dcf517c37b)

### Describe the behavior you expected

The graphs should scale in height like the other graps do.

### Steps to reproduce the issue

1.Add energy-usage-graph, energy-gas-graph or energy-water-graph
2.
3.
...

### What version of Home Assistant Core has the issue?

2025.2.0b0

### What was the last working version of Home Assistant Core?

2025.1.x

### In which browser are you experiencing the issue?

Edge 132.0.2957.127

### Which operating system are you using to run this browser?

Windows 11 Pro

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
This should be fixed in the latest beta 👍

**Comment by VinceRMP** [comment]
The problem is still there when using the energy graphs on b9.
When using the auto setting for rows it is the large image and if I set the number of rows to 3 (like it was with auto) this happens:

![Image](https://github.com/user-attachments/assets/2de20905-561e-45f5-90ff-77d588faf938)

Because those cards aren't supported yet in the sections dashboard I moved to the statistics graphs with the use of "energy_date_selection: true" this gives almost the same result as it was:

![Image](https://github.com/user-attachments/assets/2737b48b-b0c2-4572-a424-a3549db34e04)

But I don't see the time from 0:00 till 23:59 and miss peak and off peak colors.
Not the biggest deal but would be nice to have that back :)

**Comment by VinceRMP** [comment]
b11 has solved the problem
