### ISSUE TITLE
Entity names are always truncated in echart state graph, no matter how long they are

### ISSUE THREAD

**Issue by karwosts** [home-assistant/frontend#23944]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

![Image](https://github.com/user-attachments/assets/ca345caf-dff9-4932-9966-6efaf4837d28)

No matter what name an entity has ("Sun", "Sun Long", or "Sun Long Long Long"), the last few letters are always truncated. 

We're clearly scaling the chart to attempt to fit the name, but it's odd that we scale it just slightly not long enough to fit the last letter. 

### Describe the behavior you expected

Display entire name up to a point, but truncate if it becomes too long (maybe over 25% of the card width?)

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2025.2.dev

### In which browser are you experiencing the issue?

Chrome

### Which operating system are you using to run this browser?

Microsoft Windows 10 Home
10.0.19045 Build 19045

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### Javascript errors shown in your browser console/inspector

```txt

```

**Comment by MindFreeze** [comment]
fixed now

**Comment by karwosts** [comment]
@MindFreeze - my trivial example still looks exactly the same at head dev this morning. 

![Image](https://github.com/user-attachments/assets/6ccbd849-ba05-4828-804a-9957d8c7601d)

Are you sure this was fixed?

**Comment by MindFreeze** [comment]
Works on my machine :)
The font in your screenshot looks different though. Do you have customizations for it?
I measure the width of the text at 12px size and no bolding so customizations can mess with this.
Have think about accounting for this.

**Comment by karwosts** [comment]
Hmm no to my knowledge I don't have any customization. 

![Image](https://github.com/user-attachments/assets/5cd389de-e541-4817-959a-9d8a65140195)

This is just a brand new devcontainer setup running w/ chrome browser.

**Comment by karwosts** [comment]
Same in safe mode:

![Image](https://github.com/user-attachments/assets/777e8e40-6b28-4e6f-afef-13c6e2f5b59b)

**Comment by MindFreeze** [comment]
@bramkragten @piitaya Can you reproduce this? It shoul only cut off long labels.
We can add 1-2 pixels extra width but I don't want to do it blindly

**Comment by karwosts** [comment]
Improved but still not perfect... got a little clipping on the left now in addition to ellipsis on the right.

![Image](https://github.com/user-attachments/assets/3b54118e-ccbe-432d-9276-aba091545b6d)

**Comment by karwosts** [comment]
If this is really something wrong with my local enviroment I'll close this and stop complaining, but was just curious if it was determined why this shows for mine but not others.

**Comment by piitaya** [comment]
It's hard to reproduce because looks like it depends of the OS and the browser.

**Comment by MindFreeze** [comment]
@karwosts pls try the latest fix. To be clear, there is a max width on the label that depends on the card width. But short labels should fix and there shouldn't be clipping on the left

**Comment by karwosts** [comment]
I pulled new dev but I don't really see any change 😕 

![Image](https://github.com/user-attachments/assets/312f24db-dec3-41fb-a2ab-5079c9cc1267)

**Comment by MindFreeze** [comment]
"Sun" works
"Sun long" Shouldn't be cutoff on the left. I haven't seen that since we fixed it and I was testing for it specifically.
The others look correct but why are they cut off at different widths? They should be the same.

@piitaya @bramkragten You can't reproduce these issues anymore either right?

**Comment by silamon** [comment]
I think it still exists in some form. At least, I can still see the cutoff on the left in the demo instance:  

![Image](https://github.com/user-attachments/assets/d8fb5ccf-fb60-43b1-8a79-2ba4440e8788)

**Comment by silamon** [comment]
Using the latest dev with demo integration: 

![Image](https://github.com/user-attachments/assets/0f8d015a-9661-49a3-acdd-fb21f28c56f1)

**Comment by MindFreeze** [comment]
@silamon which OS and Browser do you have? I don't see this

**Comment by MindFreeze** [comment]
I managed to reproduce it on Windows Edge. Seems to be windows specific

**Comment by silamon** [comment]
It's a Windows OS with Google Chrome as browser. I've doubled the labelMargin already since I think it applies to the left and the right of the label.

**Comment by MindFreeze** [comment]
It's the font. The charts default to some Microsoft font on Windows. We wanted to set an explicit font anyway. Just have to do it sooner
