### ISSUE TITLE
Integration page Configure Popup title padding

### ISSUE THREAD

**Issue by holdestmade** [home-assistant/frontend#25341]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Get this on 2025.5.b5 with all the configure popups in the integrations page:

Title has no left padding

![Image](https://github.com/user-attachments/assets/dacff407-e1ad-474c-9a66-6fc2203b6e9b)

### Describe the behavior you expected

Padding to left of title

### Steps to reproduce the issue

1. Integrations Page
2. Click on an integration
3. Click on a device 'configure' 
...

### What version of Home Assistant Core has the issue?

2025.5.b5

### What was the last working version of Home Assistant Core?

2025.4

### In which browser are you experiencing the issue?

Chrome Version 135.0.7049.115 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### Javascript errors shown in your browser console/inspector

```txt

```

**Comment by wendevlin** [comment]
@holdestmade please test again with b7. Should be fixed already

**Comment by holdestmade** [comment]
No still the same for me on b8

![Image](https://github.com/user-attachments/assets/474611e6-60d3-4abc-bf17-9103567b5c5a)

**Comment by holdestmade** [comment]
Perfect, many thanks

![Image](https://github.com/user-attachments/assets/f26a61f9-b148-477f-b444-2ef4a50f0b63)
