### ISSUE TITLE
Single row tiles contents misaligned vertically

### ISSUE THREAD

**Issue by dulek** [home-assistant/frontend#25745]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

This is within the Android companion app, but home-assistant/android#5403 got me redirected here. The single row tiles are misaligned with certain system font and interface sizes. For example with this setting (font on top, interface elements bottom):

![Image](https://github.com/user-attachments/assets/0f73c499-0108-4941-8615-e235ba77c6fb)

Lovelace tiles looks like this:

![Image](https://github.com/user-attachments/assets/29099537-f950-4d15-866a-d64cad72b7bb)

You can see that tile contents are not centered vertically, but shifted to the bottom.

This is obviously not happening in mobile web browser, as then the elements do not derive size from the system settings. I'm using the Sections dashboard type.

### Describe the behavior you expected

I'd expect the contents of tiles to be vertically aligned regardless of my system font settings.

### Steps to reproduce the issue

1. Setup Android system font setting like on the screenshots.
2. Create a Sections dashboard with single row Tiles.
3. Observe the results.
...

### What version of Home Assistant Core has the issue?

core-2025.5.3

### In which browser are you experiencing the issue?

Android Companion app 2025.5.3-full

### Which operating system are you using to run this browser?

Android 15

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt

```

**Comment by Aasikki** [comment]
At least for me they are still slightly misaligned even at normal font size and even on my PC. It's just hearder to notice but it's definitely misaligned. Changing the font size on Android just makes it more pronounced.

**Comment by MelvinSnijders** [comment]
> At least for me they are still slightly misaligned even at normal font size and even on my PC. It's just hearder to notice but it's definitely misaligned. Changing the font size on Android just makes it more pronounced.

Same here, although not on desktop, but definitely some misalignment in the mobile app.

![Screenshot_20250926_112802_Home Assistant.jpg](https://github.com/user-attachments/assets/a4bcb8e4-9be2-49f4-a58b-f9214ffaf93b)

**Comment by bt1v1** [comment]
I have the same problem on my Pixel 10 Pro, Android 16. I enlarged the view in the Android system settings. The tile cards are then vertically misaligned.
If I change these to Mushroom Cards the problem doesn't exist. They are then correctly aligned.

**Comment by MelvinSnijders** [comment]
This is still an issue for me on the latest HomeAssistant version

**Comment by torge70** [comment]
This is still an issue on my Google Pixel 9 with Android 16 from may 2026 and app version 2026.4.4.
Some combinations of text sizes can make this really bad.

<img width="1008" height="2244" alt="Image" src="https://github.com/user-attachments/assets/f00ac394-b79e-4f17-9951-a43d30ee794c" />

**Comment by piitaya** [comment]
Hi @torge70, are you using a custom theme? The row height looks very narrow.

**Comment by torge70** [comment]
> Hi [@torge70](https://github.com/torge70), are you using a custom theme? The row height looks very narrow.

Hi @piitaya,
This is plain HA without any custom theme.

**Comment by piitaya** [comment]
Oh right, the issue should be fixed in core 2026.5.2 and you are on 2026.4.4.

**Comment by space-cataz** [comment]
I just updated to Core 2026.5.2 and I'm still seeing the issue on my Pixel 10 unfortunately. I cleared the app and cache data on the app as a troubleshooting step. Attached are screenshots of the Tile card on Mobile and my Macbook Pro

<img width="912" height="2048" alt="Image" src="https://github.com/user-attachments/assets/cf1768c5-7871-4d55-bfb7-f508cbfbd70c" />

<img width="948" height="229" alt="Image" src="https://github.com/user-attachments/assets/6b71d9d8-029a-4d2b-85c7-fd394404e998" />

**Comment by piitaya** [comment]
Oh my bad, the fix is merged but will be available in 2026.6 release.
