### ISSUE TITLE
Sensor card sometimes showing line data of previous graph when multiple instances on a dashboard on Android client

### ISSUE THREAD

**Issue by nevvob** [home-assistant/frontend#26065]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have a dashboard that has 11 temperature sensor cards on it.  Some cards whilst showing their line data they are also showing the data of the previous graphs card.  Below are two screen grabs of the top and bottom part of the dashboard: 

![Image](https://github.com/user-attachments/assets/29ea543e-087c-492e-8bad-ad2f0e95ea48)

![Image](https://github.com/user-attachments/assets/6fb95767-0c28-494f-8339-7d7c975ae64b)

Adding and removing cards does not always cause the same positional card to duplicate.  The duplication is random and also happens across different sections on the same page.

Opening the same dashboard in brave browser on the same device does not exhibit the same behaviour.

### Describe the behavior you expected

Line graph data displayed as expected.

### Steps to reproduce the issue

1.  Create a dashboard
2.  Add multiple sensor cards using line mode.

### What version of Home Assistant Core has the issue?

2025.7.0

### In which browser are you experiencing the issue?

Android client 2025.6.6-full

### Which operating system are you using to run this browser?

Android version 15

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt

```

### Additional information

This issue is not new to the latest release of Home Assistant / the Android client, it has been around for at least 4 months when I got all the sensors. I just haven't reported it before.

**Comment by nevvob** [comment]
Closed as created new issue in correct place.  https://github.com/home-assistant/android/issues/5500

**Comment by nevvob** [comment]
Reopening here as this was the correct location.  

As requested my version of WebView as installed is:  137.0.7151.116

**Comment by dpvfx** [comment]
I am having the same issue on a Samsung S25 Ultra. I opened an issue and didn't realize it was already reported. Sorry about that!

I just wanted to post here to note that it does not happen in the Chrome browser app. In this phone, it only happens in the HA Android App. Also, it does not happen in my previous Samsung Note 10+, nor in my wife's iPhone 12.

**Comment by nevvob** [comment]
Probably worth noting that my device is also an S25, but not the Ultra.

**Comment by ishbuggy** [comment]
Same issue here, that I can only reproduce this on an S25+, and not on an S24 or S20FE.

**Comment by rydercowan** [comment]
Same experience with Fold7 running OneUI8/Android 16. The cover display and inner display, although to a lesser extent, are both affected. Problem not seen on Fold6 running OneUI7/Android 15.

**Comment by USA-RedDragon** [comment]
Also seeing this on a Z Fold 7 with Webview version 139.0.7258.144 on Android 16

**Comment by johan-cb** [comment]
I have the same issue for months now, never really took time to look for an existing bug ticket up until now.

Running the latest companion app. Samsung S21 and Samsung S25.

![Image](https://github.com/user-attachments/assets/98f962d1-3b85-4075-946c-52cf1dc74462)

**Comment by rydercowan** [comment]
There appears to have been a change to sensor card display processing in HA Core 2025.11.0. The problem reported here is still present, but graph lines are very much less smoothed than previously. Possibly the data aggregation has been changed.

**Comment by rydercowan** [comment]
There appears to have been a change to sensor card display processing in HA Core 2025.11.0. The problem reported here is still present, but graph lines are very much less smoothed than previously. Possibly the data aggregation has been changed?

The attachments show the same sensor cards, as displayed on Windows, not mobile, immediately after (top image) and immediately before (bottom image) updating to 2025.11.0. However, the same effect is seen on my Fold7.

![Image](https://github.com/user-attachments/assets/f23d54b1-13ad-4ba4-b63b-77c7feadb1df)
![Image](https://github.com/user-attachments/assets/464a0dff-92a4-429f-87e4-2168ab4eae93)

**Comment by ESDN83** [comment]
Same issum for me... everything up to date s25 ultra... 
2025.11.1,  appversion 2025.8.7-full

![Image](https://github.com/user-attachments/assets/74d6e0ae-a92b-4405-9fc4-5187568d7c93)

**Comment by Kuj0n** [comment]
I have the same problem for a long time on s25 ultra. What is weird, s24 fe is not affected.
When I edit the dashboard, all charts are displayed correctly, but when the editing is closed, it becomes a mess.

**Comment by vrststn** [comment]
Good news, I just found out that if you use a custom theme, the problem is resolved.
I installed another theme and noticed the glitch was gone!

Edit: I only tested one theme: "graphite".

<img width="562" height="305" alt="Image" src="https://github.com/user-attachments/assets/d0020c74-6c3e-43e0-ac17-75cb778a1cb0" />

**Comment by Kuj0n** [comment]
Which theme did you use?
For me changing theme didn't help. 

![Image](https://github.com/user-attachments/assets/f78bc890-c897-4b80-8513-a33c4a0044a1)

**Comment by vrststn** [comment]
The one I used is "graphite". I indeed only tested one...
You can find it on HACS.

**Comment by Drums7** [comment]
> Good news, I just found out that if you use a custom theme, the problem is resolved. I installed another theme and noticed the glitch was gone!
> 
> Edit: I only tested one theme: "graphite".
> 
> <img alt="Image" width="562" height="305" src="https://private-user-images.githubusercontent.com/211344151/520384849-d0020c74-6c3e-43e0-ac17-75cb778a1cb0.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQ1ODI3OTYsIm5iZiI6MTc2NDU4MjQ5NiwicGF0aCI6Ii8yMTEzNDQxNTEvNTIwMzg0ODQ5LWQwMDIwYzc0LTZjM2UtNDNlMC1hYzE3LTc1Y2I3NzhhMWNiMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTIwMVQwOTQ4MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNDVkZGZiNjBlOTM5NGM3YjI3MjU5Y2MxZjhiYjM1OTE2OTkyNDg5M2FmYzFlNDZhMDJjMTM2MDRhNmVlN2MxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fXvrPn67bDOmmyDR-FhAmoTFv5_nzzuxUp4arEadAnI">


"It works!!! Thank you very much, maybe this narrows down the problem — it seems that the default theme is the one causing the issue."

**Comment by rickscherer** [comment]
Can also confirm that switching theme to Graphite resolved the problem on my S25 Ultra.

**Comment by Kuj0n** [comment]
I can confirm that graphite is working fine on s25ulta but cappuccino was not.
Funny that default theme is working without any problem on s24fe.

**Comment by dpvfx** [comment]
WOW much awaited!!!! 

I can also confirm the graphite theme fixed the issue on all my devices. So, theres something in the default theme that breaks the graphs. Interesting! 

For now this is good --and BTW, the graphite theme is not bad at all. 

Thank you all!

![Image](https://github.com/user-attachments/assets/1a7656bd-db0a-496e-b878-ee8b70175eb1)

**Comment by jhol-byte** [comment]
I just tested some minimal theme, for me the following entry to frontend configuration fixes the rendering issue:
```
  themes:
    jh-display:
      modes:
        light:
          # border color of cards
          divider-color: "#e0e0e0"
```

**Comment by rydercowan** [comment]
That's worked for me on Galaxy Fold7, for both cover and inner display. 

Many thanks.

**Comment by Drums7** [comment]
> I just tested some minimal theme, for me the following entry to frontend configuration fixes the rendering issue:

> 
> ```
>   themes:
>     jh-display:
>       modes:
>         light:
>           # border color of cards
>           divider-color: "#e0e0e0"
> ```
Solved!!! Thank you so much!!!, sharing here the Dark version:

> 
> ```
>   themes:
>     jh-display:
>       modes:
>         dark:
>           # border color of cards
>           divider-color: "#343434"
> ```
changing light to dark and the color to #343434 is enough.

Edit:
And can’t this be reported to the Home Assistant developers so they can fix it? I honestly don’t know how any of this works…

**Comment by jhol-byte** [comment]
seems to be fixed in Frontend 20251203.0

**Comment by Drums7** [comment]
In my case, with the 2025-12-03 version it has gotten worse. Yesterday it was fixed with jh-display, but today with the new version it doesn’t get fixed. It looks bad with the default theme and with jh-display.

**Comment by jhol-byte** [comment]
You are right: not fixed, for my dashboard portrait mode looks correct now, but landscape still broken. Theme jh-display still fixes it for my dashboard though.

**Comment by nickneos** [comment]
Did a google search for this issue as its been bugging me for a while and found this open issue.

Just wanted to add that I am also experiencing the same on an S25 Ultra. 

Using the graphite theme someone else mentioned above, which resolves the issue, although it would be good to have a fix independent of which theme is selected.

**Comment by rfontijn** [comment]
Issue still present with latest versions of ha and  companion app.

<img width="1080" height="808" alt="Image" src="https://github.com/user-attachments/assets/a23a0ce5-c2e1-4ae0-ba42-834089cea39c" />

**Comment by elliotbeaumont52-bit** [comment]
Bump

**Comment by johan-cb** [comment]
Still impacted:

Home Assistant OS
Core
2026.3.1
Supervisor
2026.03.0
Operating System
17.1
Interface utilisateur
20260304.0
Application Companion
2026.3.2-full (20802)

**Comment by MindFreeze** [comment]
I can't reproduce it anymore :(

**Comment by rfontijn** [comment]
I have same versions as @johan-cb , still reproducable, but when clicked on one of the graphs and going back, I think a refresh event occurs, and then it looks ok. 
Restarting the app makes is broken again. Looks like some weird behavior of the companion app.

**Comment by jLynx** [comment]
Same issue. It's really annoying

**Comment by MindFreeze** [comment]
Is everyone still getting this only on Samsung devices?

**Comment by jLynx** [comment]
I am Samsung, yes

**Comment by johan-cb** [comment]
This is solved for me with 2026.3.2-full (20802)

**Comment by rfontijn** [comment]
Yes still present with latest versions.

**Comment by jLynx** [comment]
Smae here, still having the issue with the latest version

**Comment by masdaster** [comment]
I'm on the latest version and facing this issue too on my OnePlus device.
