### ISSUE TITLE
Picture-elements card displays static image with `camera_view: live` enabled

### ISSUE THREAD

**Issue by jparthum** [home-assistant/frontend#4629]
## Checklist

- [✓ ] I have updated to the latest available Home Assistant version.
- [✓ ] I have cleared the cache of my browser.
- [✓ ] I have tried a different browser to see if it is related to my browser.

## The problem

The `picture-elements` card refreshes a static image every 10 seconds as though `camera_view: live` were omitted from the card configuration.

## Expected behavior

Since the documentation lists `camera_view: live` as a valid option for the [picture-elements](https://www.home-assistant.io/lovelace/picture-elements/#camera_view) card, I expected the video to stream within the card view as with the other two cards listing the same option; [picture-entity](https://www.home-assistant.io/lovelace/picture-entity/#camera_view), and [picture-glance](https://www.home-assistant.io/lovelace/picture-glance/#camera_view).

## Steps to reproduce

The code in "Problem-relevant configuration" can be pasted into `ui-lovelace.yaml` and the resulting View (![mdi:test-tube](https://i.imgur.com/4j9r3NN.png)/ "Camera Testing") will show three camera cards:

![Camera Testing View Screenshot](https://i.imgur.com/yr7NMlQm.png)

The `picture-entity` and `picture-glance` cards (left-hand column in above image) will display streaming video and the remaining `picture-elements` card will not.

## Environment

- Home Assistant release with the issue: 
  - 0.104.3 (venv)
- Last working Home Assistant release (if known): 
  - Not sure, but has not worked in the previous 5 or 6 releases.
- UI Type (States or Lovelace): 
  - Lovelace
- Browser and browser version: 
  - Chrome ver. 79.0.3945.130 (desktop)
  - Chrome ver. 79.0.3945.136 (Android)
- Operating system: 
  - Windows 7 (64-bit)
  - Android 9

## Problem-relevant configuration

```yaml
#### Camera Test View ####

  - title: Camera Testing
    path: camera_test
    icon: mdi:test-tube
    cards:

      - type: picture-entity
        entity: camera.MY_CAMERA
        camera_image: camera.MY_CAMERA
        camera_view: live

      - type: picture-glance
        entities: []
        camera_image: camera.MY_CAMERA
        camera_view: live

      - type: picture-elements
        # Base image to set 16:9 Aspect Ratio
        image: https://i.imgur.com/FHZLxXp.png
        elements:
          - type: image
            camera_image: camera.MY_CAMERA
            camera_view: live
            style:
              left: 50%
              top: 50%
              width: 100%
              height: 100%
```
## Javascript errors shown in your browser console/inspector

```txt
No errors.
```

## Additional information
While looking through the source code (in the hopes of being a contributor instead of a leech), I noticed that `<div id="root">` is not present in the code for the working cards.  This seems to have been [removed](https://github.com/home-assistant/home-assistant-polymer/commit/6b730b7c403675bc6a3035fc67a9b30723b8c270#diff-c8c7462dbe653c3db3bbcf9e0140e54c) from `hui-picture-elements-card.ts` at the same `state_image` and `camera_image` were originally added, and then [replaced](https://github.com/home-assistant/home-assistant-polymer/commit/647a33ea61539ec9d691a0d0f0f2eb75a8934acc#diff-c8c7462dbe653c3db3bbcf9e0140e54c) shortly after.  I don't know if this is related to the issue, I just thought I'd point it out in case it helps diagnosing in some way.

**Comment by aptonline** [comment]
I'm seeing the same issue, any chance this bug can be reopened?

**Comment by jparthum** [comment]
@aptonline :  Here's a workaround <https://community.home-assistant.io/t/streaming-camera-in-picture-elements/114209/18>.
Hope this helps.

**Comment by bramkragten** [comment]
I think I fixed this with #5880

**Comment by mynameisdaniel32** [comment]
Just came across this issue in 0.110.2 still - streaming works in picture-entity cards, but not picture-elements > image

**Comment by tnagels** [comment]
Sorry to have to ask this, but it seems this bug is not fixed. I still have this problem on HA 0.118.5

**Comment by cinzas** [comment]
Still exists. Running HA 2020.12.2

**Comment by vmakeev** [comment]
Still reproduce, 2021.9.3. Can you please reopen it again?
