### ISSUE TITLE
Theme / CSS inheritance when using a theme per view or theme per dashboard in Lovelace

### ISSUE THREAD

**Issue by scottsweb** [home-assistant/frontend#5460]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I have two themes configured. `theme_a` and `theme_b`. Theme A is a light theme that I use as the default for HA. Theme B is a dark theme used for a specific view or a specific dashboard (the new functionality) only. An example Lovelace config looks like so:

```
views:
  - title: Dark Section
    icon: mdi:tablet
    theme: theme_b
    path: tablet
```

I am struggling with inheritance and contamination of styles between the two themes. In `theme_a` for example, I have defined: `paper-item-icon-active-color` as a yellow colour `#FDD835`. I have then chosen a different colour in `theme_b`: `paper-item-icon-active-color: '#3182b7'` but I am still seeing items in yellow on the Dark Section view.

It is worth noting that I am using the theme refresh service after every change: frontend.reload_themes but it doesn’t fix the issue.

I wondered if there is some trick I am missing when using a theme for a specific view? … or is it simply not possible for a single view to control some CSS properties?

An example:

<img width="1021" alt="Screenshot 2020-04-05 at 17 40 52" src="https://user-images.githubusercontent.com/411945/78503214-8382a180-7765-11ea-8839-0957bcf6694c.png">

And the config for the two themes can be found here: https://github.com/scottsweb/ham/blob/master/homeassistant/themes.yaml

## Expected behavior

A child theme should be respected and the master theme should be ignored.

## Steps to reproduce

1. Create two themes as per: https://github.com/scottsweb/ham/blob/master/homeassistant/themes.yaml
2. Set `syamore` as your main theme and then `slate` as the theme on a specific view
3. See that some colours in the slate theme are not respected

## Environment

```
arch | armv7l
dev | false
docker | true
hassio | false
os_name | Linux
os_version | 4.19.97-v7l+
python_version | 3.7.3
timezone | Europe/Stockholm
version | 0.107.7
virtualenv | false
```

- Home Assistant release with the issue: 0.107.x
- Last working Home Assistant release (if known): N/A
- Browser and browser version: Chrome / Firefox
- Operating system: OSX

**Comment by bramkragten** [comment]
Fixed in 0.108

**Comment by scottsweb** [comment]
I have tested `0.108` and this is still an issue unfortunately. Exactly the same behaviour.

**Comment by zsarnett** [comment]
MAke sure to clear the cache in your browser

**Comment by scottsweb** [comment]
<img width="1384" alt="Screenshot 2020-04-09 at 22 29 41" src="https://user-images.githubusercontent.com/411945/78937999-b86a5d80-7ab1-11ea-8a18-114049930395.png">

I have dev tools open with caching disabled and still see the same results. The parent theme interferes with the child theme. Testing on `0.108.1`
