### ISSUE TITLE
Don't automatically convert states to strings in automations

### ISSUE THREAD

**Issue by pascallj** [home-assistant/frontend#7231]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

Now that we can use the numeric state and state triggers/conditions on attributes as well (home-assistant/core#41261), the frontend shouldn't automatically convert the `from`, `to`, `above`, `below` and `state` fields to strings as attributes don't necessarily have to be strings.

This could be classified as either a bug or a feature request, but as the current implementation isn't intuitive, I chose bug.

## Expected behavior

If and only if an attribute is selected:
* The fields `above` and `below` should never be converted to strings as they are always numeric values
* For every other field:
    * The values `true` and `false` should not be converted to strings
    * Numeric values should not be converted to strings

## Steps to reproduce

Add a numeric state trigger on `sun.sun` attribute `elevation` to be below 1 degree. It should be entered in YAML as:

```yaml
platform: numeric_state
entity_id: sun.sun
attribute: elevation
below: 1
```

## Environment

- Home Assistant release with the issue: 0.116.0b3
- Last working Home Assistant release (if known): Feature only works since 0.116.0b3
- Browser and browser version: Irrelevant
- Operating system: Irrelevant

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by pascallj** [comment]
Nope the automation editor still screws these kinds of automations up so if saved using the editor afterwards, the automations don't work anymore.

**Comment by bramkragten** [comment]
We will probably remove attribute support from the UI editor

**Comment by pascallj** [comment]
Why if I may ask? Is there a better alternative?

This was one of the most useful changes since a long time. Almost every automation I have uses attributes in one way or another. Implementing this in the UI editor made it a lot more user friendly.

**Comment by bramkragten** [comment]
Because it is an advanced option, and making a good working UI for it is hard.

The alternative would be to show it as an YAML field.

**Comment by pascallj** [comment]
The bug is still there and attribute support is still present. If attribute support is going to be removed, maybe it's better to label this and related issues as 'wontfix' and be done with it.

**Comment by bramkragten** [comment]
This should still be solved

**Comment by chilicheech** [comment]
How is this already solved? I have the latest hass and the issue is still present..

## System Health

version | core-2021.7.4
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
virtualenv | false
python_version | 3.9.5
os_name | Linux
os_version | 5.11.0-25-generic
arch | x86_64
timezone | America/Los_Angeles

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.13.2
Stage | running
Available Repositories | 848
Installed Repositories | 11

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 49

</details>

<details><summary>Lovelace</summary>

dashboards | 4
-- | --
resources | 6
views | 13
mode | storage

</details>

**Comment by pascallj** [comment]
It's not. This issue still open.

**Comment by emontnemery** [comment]
Fixed by home-assistant/frontend#10811

**Comment by pascallj** [comment]
The 'number case' for above and below seems to be really solved, as in it now even works when the number is enclosed in single quotes. I don't think that is solved by #10811 though, as far as I can see.

However the from and to 'state case' is bypassed. It only solves the fact that the automation editor screws up the automation every time you want to edit it because that block is 'not supported'. I really appreciate this is bypassed now.

However it is still counter intuitive that if you want to make an automation trigger on the 'rising' attribute of the Sun entity, that if you just enter true or false in the editor, it doesn't work. Of course there is the Sun trigger type for this specific case, but for any other boolean attribute or an exact number in a from and to trigger, you still have to use YAML.

**Comment by emontnemery** [comment]
@pascallj There's some discussion around this in https://github.com/home-assistant/frontend/issues/7708
