### ISSUE TITLE
Issues with macOS 12 Monterey Safari (and iOS 15 Mobile Safari)

### ISSUE THREAD

**Issue by nickroberts** [home-assistant/frontend#9394]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

For the latest developer beta of macOS Monterey (and iOS 15 Mobile Safari), it looks like the websocket connection is failing.

Here is a screenshot of the console. It's about as much as I could get, as it keeps happening over and over, so you are unable to really do anything.

![CleanShot 2021-06-08 at 16 08 13](https://user-images.githubusercontent.com/972330/121251179-96ff3000-c874-11eb-954f-56f6a1c2e850.png)

### Describe the behavior you expected

It should load the dashboard, along with all of my entities.

### Steps to reproduce the issue

1. Install the latest version of macOS 12 Monterey
2. Open Safari to your HA installation
3. Login

### What version of Home Assistant Core has the issue?

2021.6.3

### Additional information

I also created an issue over on the iOS repo: https://github.com/home-assistant/iOS/issues/1655

**Comment by labzilla** [comment]
I can confirm that I am also receiving this error after upgrading to macOS 12 Monterey Beta 21A5248P, which has Safari 12 v 17612.1.15.1.14. I am running HA 2021.6.4. 

Here's the output of the developer console:
```
[Warning] The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'. (app.bcb38ac1.js, line 849)
[Error] WebSocket connection to 'wss://homeassistant.example.com/api/websocket' failed: The operation couldn’t be completed. (kNWErrorDomainPOSIX error 40 - Message too long)
[Log] {type: "result", success: false, error: {code: 3, message: "Connection lost"}} (chunk.53899b0337677dfbe7ab.js, line 592)
[Error] Unhandled Promise Rejection: [object Object]
	promiseEmptyOnRejected
	promiseReactionJob
[Error] Unhandled Promise Rejection: [object Object]
	(anonymous function) (app.bcb38ac1.js:1275:442404)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
[Error] Unhandled Promise Rejection: [object Object]
	promiseEmptyOnRejected
	promiseReactionJob

```
This is also occuring on iOS 15 in Safari, and in the HomeAssistant app. The developer console for Safari gives the following errors:
```
[Warning] The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'. (app.bcb38ac1.js, line 849)
[Error] WebSocket connection to 'wss://homeassistant.example.com/api/websocket' failed: The operation couldn’t be completed. (kNWErrorDomainPOSIX error 40 - Message too long)
[Error] Unhandled Promise Rejection: [object Object]
	(anonymous function) (app.bcb38ac1.js:1275:442404)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
[Error] Unhandled Promise Rejection: [object Object]
	promiseEmptyOnRejected
	promiseReactionJob
[Error] SyntaxError: JSON Parse error: Unexpected EOF
	parse (core.7ce1f920.js:1:9042)
	_handleMessage (core.7ce1f920.js:1:9042)

```

**Comment by bramkragten** [comment]
Tracked here: https://bugs.webkit.org/show_bug.cgi?id=227030

**Comment by nickroberts** [comment]
I read somewhere that they broke Indexedb, too. I really want to use Safari, but things like this keep me using other browsers.

That being said, I know it is beta software, but c’mon, Apple!

**Comment by nickroberts** [comment]
Just tested iOS 15 beta 2. No changes. Hopefully they figure out the issue soon! I miss being able to use HA from my phone, but still can use a different browser on my Mac and PC.

**Comment by bramkragten** [comment]
Fixed upstream (probably not released yet)

**Comment by nickroberts** [comment]
I was hoping this was released with Monterey Beta 2, but sadly, it looks like it didn't include the fix. I updated, and HA is still broken in Safari. Hopefully the next iOS 15 Beta fixes the issue. It's a tab bit annoying not being able to control anything with my phone. First world problems!

**Comment by nibblerrick** [comment]
> Fixed upstream (probably not released yet)

Thanks for letting us know @bramkragten, upstream means on apples side or in a component used by ha? Would be nice to know.

**Comment by bramkragten** [comment]
Apple committed a patch

**Comment by nibblerrick** [comment]
Thank you!

**Comment by nickroberts** [comment]
Looks like on both Monterey Beta 3 and iOS 15 Beta 3, everything is working, again! Woo-hoo!
