### ISSUE TITLE
UI for automations destroys code in automation

### ISSUE THREAD

**Issue by Friedi1970** [home-assistant/frontend#9753]
### The problem

I have an automation or two where I have the following code within the actions:
```
  action:
  - service: notify.bewohner
    data:
      message: >
        '{% if is_state_attr("sensor.ics_6", "remaining",2) %} ...
```

My problem now is, everytime when I create a new automation with the GUI (settings -> automations) the code will be destroyed. The system deletes the > sign. Furthermore the line breaks will be deleted.

### What is version of Home Assistant Core has the issue?

core-2021.8.4

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Automations

### Example YAML snippet

```yaml
- id: kellerreinigung_msg
  alias: Benachrichtigung zur Kellerreinigung
  trigger:
  - platform: time
    at: '16:00'
  condition:
    condition: or
    conditions:
    - condition: template
      value_template: '{{ state_attr(''sensor.ics_6'', ''remaining'') == 7 }}'
    - condition: template
      value_template: '{{ state_attr(''sensor.ics_7'', ''remaining'') == 7 }}'
    - condition: template
      value_template: '{{ state_attr(''sensor.ics_8'', ''remaining'') == 7 }}'
  action:
  - service: notify.bewohner
    data:
      message: >
        {% if is_state_attr("sensor.ics_6", "remaining",2) %} Nächste Woche ist die Familie {{states.sensor.ics_6.attributes.description}} mit der Kellerreinigung dran.{% endif %}
        {% if is_state_attr("sensor.ics_7", "remaining",7) %} Nächste Woche ist die Familie {{states.sensor.ics_7.attributes.description}} mit der Kellerreinigung dran.{% endif %}
        {% if is_state_attr("sensor.ics_8", "remaining",7) %} Nächste Woche ist die Familie {{states.sensor.ics_8.attributes.description}} mit der Kellerreinigung dran.{% endif %}
  initial_state: 'on'
  mode: single
```

**Comment by rudyberkvens** [comment]
I think I have the same issue. 

`      - conditions:
          - condition: state
            entity_id: input_select.a_lign_teams_activity
            state:
              - In A Call
              - Presenting
              - In A Conference Call`
Turns into 

`      - conditions:
          - condition: state
            entity_id: input_select.a_lign_teams_activity
            state: In A Call,Presenting,In A Conference Call`

Which does breaks the automation.

## System Health

version | core-2021.8.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.6
os_name | Linux
os_version | 5.10.53
arch | x86_64
timezone | America/Chicago

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.13.2
Stage | running
Available Repositories | 908
Installed Repositories | 13

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | August 24, 2021, 7:00 PM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.2
-- | --
update_channel | stable
supervisor_version | supervisor-2021.06.8
docker_version | 20.10.6
disk_total | 30.8 GB
disk_used | 21.5 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | FTP (4.2.0), Glances (0.12.3), Samba share (9.5.1), Mosquitto broker (6.0.1), Node-RED (9.2.1), Portainer (1.5.1), Grafana (7.0.4), TasmoAdmin (0.15.0), Visual Studio Code (3.6.1), InfluxDB (4.1.1), UniFi Controller (0.23.2), ESPHome (1.20.4), SSH & Web Terminal (9.0.0), Let's Encrypt (4.11.0), NGINX Home Assistant SSL proxy (3.0.2), WireGuard (0.5.1), Log Viewer (0.11.1), Z-Wave JS to MQTT (0.23.2)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 11
views | 10
mode | storage

</details>

**Comment by osochor** [comment]
I can also confirm the issue concerning "state" reported by @rudyberkvens 
After you open the visual editor and you press the save button, the syntax changed and the automation is broken.

**Comment by fusion986** [comment]
The following syntax also gets clobbered:

Original: `command: [home_hold,select]`
After saving, replaced with: `command: home_hold,select`

**Comment by ScratMan** [comment]
The UI also changes some other parts of the code. I'm on 2021.9.4 core running on a Raspberry pi in docker.
I need to trigger an automation "B" when an automation "A" stops, based on the 'automation.A.current' attribute.

Code of "B" is as follows :
alias: Arrosage Automatique Terminé
description: ''
trigger:
  - platform: state
    entity_id: automation.arrosage_automatique_du_potager
    attribute: current
    from: 1
    to: 0
condition: []
action:
  - service: smart_irrigation.smart_irrigation_reset_bucket
mode: queued
max: 10

But if I use the UI to edit the automation, the values of the attribute changes to strings :
alias: Arrosage Automatique Terminé
description: ''
trigger:
  - platform: state
    entity_id: automation.arrosage_automatique_du_potager
    attribute: current
    from: '1'
    to: '0'
condition: []
action:
  - service: smart_irrigation.smart_irrigation_reset_bucket
mode: queued
max: 10

And then the automation can't trigger.

It is exactly the same issue as specified in the (closed) issues #44449 and #45601
https://github.com/home-assistant/core/issues/44449
https://github.com/home-assistant/core/issues/45601

**Comment by loeffelpan** [comment]
Same here as @rudyberkvens described.
It's annoying. I have to switch to yaml-mode any time I modify something in that automation, because the multi-state trigger are saved properly only in that way.

I think there are multi-state triggers, template code and maybe other things to be affected.
Is it useful to make single issues for the different destroyings of the UI editor?

**Comment by walking-octopus** [comment]
This issue shouldn't be closed! UI still breaks some automations or makes the YAML unreadable.

**Comment by emontnemery** [comment]
This has been fixed in 2021.12 by #10811

**Comment by StifflersMoM69** [comment]
I am on Core 2021.12.4 and still having this issue. 
It changes from
          service_data:
            device: Samsung-Fernseher
            command:
              - 5
              - 7
to

          service_data:
            device: Samsung-Fernseher
            command: 5,7

and then the command does not work anymore

**Comment by emontnemery** [comment]
@StifflersMoM69 Please give some more details, for example share the full automation

**Comment by StifflersMoM69** [comment]
It is not an automation. It is just a card in Lovelace Dashboard. But just saw, that the Code-Change only happens, when editing in UI Mode. I am using a horizontal stack with service remote.send. The sending commands are in a wrong format

`  - type: horizontal-stack
    cards:
      - type: picture
        image: /local/XYZ.png
        tap_action:
          action: call-service
          service: remote.send_command
          service_data:
            device: Samsung-Fernseher
            command: '1'
          target:
            device_id: c88385f7e94f4703770f14f8ed6d1881
        hold_action:
          action: none
      - type: picture
        image: /local/ZYX.png
        tap_action:
          action: call-service
          service: remote.send_command
          service_data:
            device: Samsung-Fernseher
            command: 5,7,8
            delay_secs: 0.4
          target:
            device_id: c88385f7e94f4703770f14f8ed6d1881
        hold_action:
          action: none`

**Comment by emontnemery** [comment]
The problem mentioned by @ScratMan is fixed in 2021.12 by #10811, but the others are maybe not.
 @rudyberkvens, @osochor, @fusion986, @loeffelpan can you please share complete examples, just sharing a short snippet or "me too" is unfortunately not helpful to make it possible to reproduce and fix the problem.

**Comment by loeffelpan** [comment]
As you wanted, here is my whole automation which is quite long.
```
alias: 'Heimkino: AVR / Digitalradio'
description: ''
trigger:
  - platform: state
    entity_id: media_player.digitradio_ir10
    from:
      - 'off'
      - unknown
    to:
      - idle
      - paused
      - playing
    id: dradio_on
  - platform: state
    entity_id: media_player.digitradio_ir10
    to: 'off'
    for: '00:00:10'
    id: dradio_off
  - platform: state
    entity_id: media_player.yamaha_receiver
    id: avr_source
    attribute: source
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: dradio_on
        sequence:
          - condition: or
            conditions:
              - condition: template
                value_template: >-
                  {{ state_attr('media_player.yamaha_receiver', 'source') !=
                  'AUDIO1' }}
              - condition: template
                value_template: >-
                  {{ state_attr('media_player.yamaha_receiver', 'source') ==
                  none }}
          - service: input_boolean.turn_off
            target:
              entity_id: input_boolean.digitradio_auto_turned_off
          - service: yamaha.select_scene
            data:
              entity_id: media_player.yamaha_receiver
              scene: Musik
      - conditions:
          - condition: trigger
            id: dradio_off
        sequence:
          - condition: state
            state: 'off'
            entity_id: input_boolean.digitradio_auto_turned_off
          - service: media_player.turn_off
            target:
              entity_id: media_player.yamaha_receiver
      - conditions:
          - condition: trigger
            id: avr_source
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: '{{ trigger.to_state.attributes.source != ''AUDIO1'' }}'
                sequence:
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: >-
                              {{ trigger.from_state.attributes.source ==
                              'AUDIO1' }}
                        sequence:
                          - service: media_player.turn_off
                            target:
                              entity_id: media_player.digitradio_ir10
                          - service: input_boolean.turn_on
                            target:
                              entity_id: input_boolean.digitradio_auto_turned_off
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: >-
                              {{ trigger.to_state.attributes.source == 'HDMI1'
                              }}
                        sequence:
                          - service: yamaha.select_scene
                            data:
                              entity_id: media_player.yamaha_receiver
                              scene: Filme/Serien
                          - service: input_select.select_option
                            data:
                              option: 50 Hz
                            target:
                              entity_id: input_select.letzte_aktion_hz
                          - service: rest_command.reload_atv
                    default:
                      - service: media_player.volume_set
                        target:
                          entity_id: media_player.yamaha_receiver
                        data:
                          volume_level: 0.6
              - conditions:
                  - condition: template
                    value_template: '{{ trigger.to_state.attributes.source == ''AUDIO1'' }}'
                  - condition: template
                    value_template: '{{ trigger.from_state.state != ''off'' }}'
                sequence:
                  - service: media_player.turn_on
                    target:
                      entity_id: media_player.digitradio_ir10
                  - service: input_boolean.turn_off
                    target:
                      entity_id: input_boolean.digitradio_auto_turned_off
              - conditions:
                  - condition: template
                    value_template: '{{ trigger.to_state.attributes.source == ''AUDIO1'' }}'
                  - condition: template
                    value_template: '{{ trigger.from_state.state == ''off'' }}'
                  - condition: template
                    value_template: '{{ states(''media_player.digitradio_ir10'') == ''off'' }}'
                sequence:
                  - service: yamaha.select_scene
                    data:
                      entity_id: media_player.yamaha_receiver
                      scene: Filme/Serien
                  - service: input_select.select_option
                    target:
                      entity_id: input_select.letzte_aktion_hz
                    data:
                      option: 50 Hz
                  - service: rest_command.reload_atv
mode: single
```

My issue were the multiple state triggers as @rudyberkvens posted.
```
trigger:
  - platform: state
    entity_id: media_player.digitradio_ir10
    from:
      - off
      - unknown
    to:
      - idle
      - paused
      - playing
    id: dradio_on
```

Hope this is helpful. I‘m fine for now. Only the initial reported issue by @Friedi1970 is kind of annoying but that makes the code just unreadable not breaks the automation.

**Comment by loeffelpan** [comment]
> This has been fixed in 2021.12 by #10811, @walking-octopus can you confirm that's the case and if it's not, provide a concrete example of something that still breaks?

I think tihs fixes #9783 instead and not this issue
